var pets_gold = 2;

var pets_dmg = {
	'all' : 2,
	'tap' : 2,
	'hero' : 4,
	'splash' : 1,
};

var reducts = {
	'gold' : 44/55,
	'helmet' : {
		'hero' : 1,
		'tap' : 1,
		'pet' : 1,
		'sc' : .6,
		'hs' : 2/3,
		'cs' : 1
	},
	'sword' : {
		'hero' : 1,
		'tap' : 1,
		'pet' : 1,
		'sc' : 1,
		'hs' : 1,
		'cs' : 1
	},
	'tap' : {
		'hero' : 0,
		'tap' : 1,
		'pet' : 1,
		'sc' : .6,
		'hs' : 1,
		'cs' : 0
	},
	'tap_hs' : {
		'hero' : 0,
		'tap' : 1,
		'pet' : 1,
		'sc' : .6,
		'hs' : .25,
		'cs' : 0
	},
	'hero' : {
		'hero' : 1,
		'tap' : .5,
		'pet' : .5,
		'sc' : .6,
		'hs' : .5,
		'cs' : 1
	},
	'ds' : {
		'hero' : 0,
		'tap' : 1,
		'pet' : 2/3,
		'sc' : .5,
		'hs' : 2/3,
		'cs' : .5
	},
	'wc' : {
		'hero' : 1,
		'tap' : .5,
		'pet' : 1,
		'sc' : 2/3,
		'hs' : .5,
		'cs' : 1
	},
	'fs' : {
		'hero' : 0,
		'tap' : 1,
		'pet' : 0,
		'sc' : .6,
		'hs' : 1,
		'cs' : 0
	},
	'sad' : {
		'hero' : 0,
		'tap' : 1,
		'pet' : 0,
		'sc' : .6,
		'hs' : 2/3,
		'cs' : 0
	},
	'crit' : {
		'hero' : 0,
		'tap' : 1,
		'pet' : 1,
		'sc' : 1,
		'hs' : 1,
		'cs' : 1
	},
	'crit_sc' : {
		'hero' : 0,
		'tap' : 1,
		'pet' : 1,
		'sc' : 0,
		'hs' : 1,
		'cs' : 1
	},
	'splash' : {
		'hero' : 0,
		'tap' : 0,
		'pet' : 1,
		'sc' : 0,
		'hs' : 1,
		'cs' : 1
	},
	'pet' : {
		'hero' : 0,
		'tap' : 0,
		'pet' : 1,
		'sc' : 0,
		'hs' : 0,
		'cs' : 0
	},
	'rev_cs' : {
		'hero' : 1,
		'tap' : 1,
		'pet' : 1,
		'sc' : 1,
		'hs' : 0,
		'cs' : 0
	},
	'cs' : {
		'hero' : 0,
		'tap' : 0,
		'pet' : 0,
		'sc' : 0,
		'hs' : 0,
		'cs' : 1
	},
	'sc' : {
		'hero' : 0,
		'tap' : 0,
		'pet' : 0,
		'sc' : 1,
		'hs' : 0,
		'cs' : 0
	},
	'hs' : {
		'hero' : 0,
		'tap' : 0,
		'pet' : 0,
		'sc' : 0,
		'hs' : 1,
		'cs' : 0
	},
	'companion' : {
		'hero' : 0,
		'tap' : 0,
		'pet' : 1,
		'sc' : 1,
		'hs' : 0,
		'cs' : 1
	},
}

var artifacts = {
	'totalAD' : 0,
  'data' : {
     'bos' : {
       'active' : 1,
       'sort' : 1,
       'name' : '暗影之书',
       'nickname' : 'BoS',
       'bonus' : ' 蜕变圣物',
       'max' : -1,
       'effect' : .05,
       'gmax' : .12,
       'grate' : .0001,
       'gexpo' : .5,
       'ad' : .3,
       'ccoef' : .7,
       'cexpo' : 2.5,
       'type' : 'multiply',
       'expo' : {
         'sum_sort' : 40
       }
     },
     'sov' : {
       'active' : 1,
       'sort' : 2,
       'name' : '瓦如恩之石',
       'nickname' : 'SotV',
       'bonus' : ' 巨人黄金',
       'max' : -1,
       'effect' : .01,
       'gmax' : .36,
       'grate' : .00018,
       'gexpo' : .5,
       'ad' : .2,
       'ccoef' : .6,
       'cexpo' : 1.8,
       'type' : 'multiply',
       'expo' : {
         'sum' : 'skill_gold'
       }
     },
     'coc' : {
       'active' : 1,
       'sort' : 3,
       'name' : '满足宝箱',
       'nickname' : 'CoC',
       'bonus' : ' 宝箱兽黄金数量',
       'max' : -1,
       'effect' : .25,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .4,
       'ccoef' : 1,
       'cexpo' : 1.8,
       'type' : 'multiply',
       'expo' : {
         'gold' : [
           'coc',
           'fairy',
           'phom',
           'all',
           'splash',
           'inactive'
         ]
       }
     },
     'hs' : {
       'active' : 1,
       'sort' : 4,
       'name' : '英勇之盾',
       'nickname' : 'HSh',
       'bonus' : ' 头目黄金',
       'max' : -1,
       'effect' : .2,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .4,
       'ccoef' : .7,
       'cexpo' : 1.8,
       'type' : 'multiply',
       'expo' : {
         'gold' : [
           'boss',
           'all'
         ]
       }
     },
     'bop' : {
       'active' : 1,
       'sort' : 5,
       'name' : '预言之书',
       'nickname' : 'BoP',
       'bonus' : ' 所有黄金',
       'max' : -1,
       'effect' : .2,
       'gmax' : .4,
       'grate' : .00015,
       'gexpo' : .5,
       'ad' : .3,
       'ccoef' : .7,
       'cexpo' : 2.2,
       'type' : 'multiply',
       'expo' : {
         'flat' : 'gold'
       }
     },
     'kb' : {
       'active' : 1,
       'sort' : 6,
       'name' : 'Khrysos腕',
       'nickname' : 'KB',
       'bonus' : ' 技能被动黄金',
       'max' : -1,
       'effect' : .3,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .3,
       'ccoef' : .7,
       'cexpo' : 1.8,
       'type' : 'multiply',
       'expo' : {
         'gold' : [
           'inactive'
         ]
       }
     },
     'zc' : {
       'active' : 1,
       'sort' : 7,
       'name' : '扎金索斯银币',
       'nickname' : 'ZC',
       'bonus' : ' 离线黄金',
       'max' : -1,
       'effect' : .6,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .3,
       'ccoef' : .7,
       'cexpo' : 1.8,
       'type' : 'multiply',
       'expo' : {
         'gold' : [
           'inactive'
         ]
       }
     },
     'gfa' : {
       'active' : 1,
       'sort' : 8,
       'name' : '崇高仙子徽章',
       'nickname' : 'GFM',
       'bonus' : ' 仙女黄金',
       'max' : -1,
       'effect' : .3,
       'gmax' : .4,
       'grate' : .00018,
       'gexpo' : .5,
       'ad' : .4,
       'ccoef' : 1,
       'cexpo' : 1.8,
       'type' : 'multiply',
       'expo' : {
         'gold' : [
           'fairy',
           'all'
         ]
       }
     },
     'coe' : {
       'active' : 1,
       'sort' : 9,
       'name' : '惠比须神银币',
       'nickname' : 'CoE',
       'bonus' : ' 溅射黄金',
       'max' : -1,
       'effect' : .3,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .5,
       'ccoef' : .7,
       'cexpo' : 1.8,
       'type' : 'multiply',
       'expo' : {
         'gold' : [
           'phom',
           'all',
           'splash'
         ]
       }
     },
     'hsw' : {
       'active' : 1,
       'sort' : 10,
       'name' : '天堂之剑',
       'nickname' : 'HSw',
       'bonus' : ' 神器伤害',
       'max' : -1,
       'effect' : .05,
       'gmax' : .4,
       'grate' : .00025,
       'gexpo' : .5,
       'ad' : 1,
       'ccoef' : .7,
       'cexpo' : 2.2,
       'type' : 'multiply',
       'expo' : {
         'flat' : 'dmg'
       }
     },
     'dr' : {
       'active' : 1,
       'sort' : 11,
       'name' : '神圣报应',
       'nickname' : 'DR',
       'bonus' : ' 所有攻击力',
       'max' : -1,
       'effect' : .1,
       'gmax' : .32,
       'grate' : .00015,
       'gexpo' : .5,
       'ad' : 1,
       'ccoef' : 1,
       'cexpo' : 2,
       'type' : 'multiply',
       'expo' : {
         'flat' : 'dmg'
       }
     },
     'dh' : {
       'active' : 1,
       'sort' : 12,
       'name' : '醉汉榔头',
       'nickname' : 'DH',
       'bonus' : ' 点击攻击力',
       'max' : -1,
       'effect' : .1,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .3,
       'ccoef' : .6,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'tap'
       }
     },
     'ss' : {
       'active' : 1,
       'sort' : 13,
       'name' : '萨摩赛克之剑',
       'nickname' : 'SS',
       'bonus' : ' 剑术攻击伤害',
       'max' : -1,
       'effect' : .1,
       'gmax' : .32,
       'grate' : .00014,
       'gexpo' : .5,
       'ad' : .5,
       'ccoef' : .7,
       'cexpo' : 2,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'sad'
       }
     },
     'tr' : {
       'active' : 1,
       'sort' : 14,
       'name' : '复仇者',
       'nickname' : 'TR',
       'bonus' : ' 暴击伤害',
       'max' : -1,
       'effect' : .1,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .2,
       'ccoef' : .6,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'crit'
       }
     },
     'hb' : {
       'active' : 1,
       'sort' : 15,
       'name' : '英雄之刃',
       'nickname' : 'HB',
       'bonus' : ' 所有英雄伤害',
       'max' : -1,
       'effect' : .15,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .5,
       'ccoef' : .7,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'hero'
       }
     },
     'tsos' : {
       'active' : 1,
       'sort' : 16,
       'name' : '风暴之剑',
       'nickname' : 'TSoS',
       'bonus' : ' 近战英雄伤害',
       'max' : -1,
       'effect' : .2,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .3,
       'ccoef' : .7,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'hero_type' : 'melee'
       }
     },
     'fb' : {
       'active' : 1,
       'sort' : 17,
       'name' : '复仇女神之弓',
       'nickname' : 'FB',
       'bonus' : ' 远程英雄伤害',
       'max' : -1,
       'effect' : .2,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .3,
       'ccoef' : .7,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'hero_type' : 'ranged'
       }
     },
     'cota' : {
       'active' : 1,
       'sort' : 18,
       'name' : '古代护身符',
       'nickname' : 'CotA',
       'bonus' : ' 法术英雄伤害',
       'max' : -1,
       'effect' : .2,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .3,
       'ccoef' : .7,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'hero_type' : 'spell'
       }
     },
     'ttt' : {
       'active' : 1,
       'sort' : 19,
       'name' : '迷你世界树',
       'nickname' : 'TTT',
       'bonus' : ' 地面英雄伤害',
       'max' : -1,
       'effect' : .2,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .3,
       'ccoef' : .7,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'hero_type' : 'ground'
       }
     },
     'hh' : {
       'active' : 1,
       'sort' : 20,
       'name' : '埃尔密斯头盔',
       'nickname' : 'HoH',
       'bonus' : ' 飞行英雄伤害',
       'max' : -1,
       'effect' : .2,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .3,
       'ccoef' : .7,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'hero_type' : 'flying'
       }
     },
     'foe' : {
       'active' : 1,
       'sort' : 21,
       'name' : '伊甸之果',
       'nickname' : 'FoE',
       'bonus' : ' 宠物伤害',
       'max' : -1,
       'effect' : .1,
       'gmax' : .4,
       'grate' : .00015,
       'gexpo' : .5,
       'ad' : .5,
       'ccoef' : .7,
       'cexpo' : 2,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'pet'
       }
     },
     'ie' : {
       'active' : 1,
       'sort' : 22,
       'name' : '感化灵药',
       'nickname' : 'IE',
       'bonus' : ' 部落大船伤害',
       'max' : -1,
       'effect' : .1,
       'gmax' : .4,
       'grate' : .00015,
       'gexpo' : .5,
       'ad' : .5,
       'ccoef' : .7,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'cs'
       }
     },
     'orc' : {
       'active' : 1,
       'sort' : 23,
       'name' : '奥莱恩护身符',
       'nickname' : 'oRC',
       'bonus' : ' 同伴伤害',
       'max' : -1,
       'effect' : .1,
       'gmax' : .4,
       'grate' : .00015,
       'gexpo' : .5,
       'ad' : .5,
       'ccoef' : .7,
       'cexpo' : 1.8,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'companion'
       }
     },
     'hos2' : {
       'active' : 1,
       'sort' : 24,
       'name' : '风暴之心',
       'nickname' : 'HoS',
       'bonus' : ' 宠物伤害加成',
       'max' : -1,
       'effect' : .005,
       'gmax' : .32,
       'grate' : .00015,
       'gexpo' : .5,
       'ad' : .5,
       'ccoef' : .7,
       'cexpo' : 2.2,
       'type' : 'multiply',
       'expo' : {
         'sum' : 'pet_dmg'
       }
     },
     'ao' : {
       'active' : 1,
       'sort' : 25,
       'name' : '太阳神之石',
       'nickname' : 'AO',
       'bonus' : ' 宠物黄金加成',
       'max' : -1,
       'effect' : .02,
       'gmax' : .32,
       'grate' : .00015,
       'gexpo' : .5,
       'ad' : .5,
       'ccoef' : .7,
       'cexpo' : 2.2,
       'type' : 'multiply',
       'expo' : {
         'sum' : 'pet_gold'
       }
     },
     'eop' : {
       'active' : 1,
       'sort' : 26,
       'name' : 'Portara的耳环',
       'nickname' : 'EoP',
       'bonus' : ' 技能被动伤害',
       'max' : -1,
       'effect' : .2,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .3,
       'ccoef' : .6,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'flat' : 'inactive'
       }
     },
     'af' : {
       'active' : 1,
       'sort' : 27,
       'name' : '仙鸟之羽',
       'nickname' : 'AF',
       'bonus' : ' 离线伤害',
       'max' : -1,
       'effect' : .5,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .3,
       'ccoef' : .6,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'flat' : 'inactive'
       }
     },
     'hos' : {
       'active' : 1,
       'sort' : 28,
       'name' : '腐化符文之心',
       'nickname' : 'CRH',
       'bonus' : ' 溅射伤害',
       'max' : -1,
       'effect' : .00025,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .3,
       'ccoef' : .6,
       'cexpo' : 1.7,
       'type' : 'pct',
       'expo' : {
         'reduct' : 'splash'
       }
     },
     'td' : {
       'active' : 1,
       'sort' : 29,
       'name' : '迪朗达尔之剑',
       'nickname' : 'DS',
       'bonus' : ' Non-Boss Damage',
       'max' : -1,
       'effect' : .24,
       'gmax' : .32,
       'grate' : .00015,
       'gexpo' : .5,
       'ad' : 1,
       'ccoef' : 1,
       'cexpo' : 2,
       'type' : 'multiply',
       'expo' : {
         'flat' : 'hsk'
       }
     },
     'hs2' : {
       'active' : 1,
       'sort' : 30,
       'name' : '冥界头骨',
       'nickname' : 'HSk',
       'bonus' : ' 魔王伤害',
       'max' : -1,
       'effect' : .12,
       'gmax' : .32,
       'grate' : .00015,
       'gexpo' : .5,
       'ad' : 1,
       'ccoef' : 1,
       'cexpo' : 2,
       'type' : 'multiply',
       'expo' : {
         'flat' : 'dmg'
       }
     },
     'roc' : {
       'active' : 1,
       'sort' : 31,
       'name' : '卡利斯托之戒',
       'nickname' : 'RoC',
       'bonus' : ' 所有装备加成',
       'max' : -1,
       'effect' : .01,
       'gmax' : .32,
       'grate' : .00015,
       'gexpo' : .5,
       'ad' : .5,
       'ccoef' : .65,
       'cexpo' : 2.2,
       'type' : 'multiply',
       'expo' : {
         'sum' : 'equip'
       }
     },
     'bod' : {
       'active' : 1,
       'sort' : 32,
       'name' : '达摩克利斯之剑',
       'nickname' : 'BoD',
       'bonus' : ' 刀剑装备加成',
       'max' : -1,
       'effect' : .08,
       'gmax' : .32,
       'grate' : .00015,
       'gexpo' : .5,
       'ad' : .5,
       'ccoef' : .65,
       'cexpo' : 2,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'sword'
       }
     },
     'hom' : {
       'active' : 1,
       'sort' : 33,
       'name' : '疯狂头盔',
       'nickname' : 'HoM',
       'bonus' : ' 头盔加成',
       'max' : -1,
       'effect' : .08,
       'gmax' : .32,
       'grate' : .00015,
       'gexpo' : .5,
       'ad' : .5,
       'ccoef' : .65,
       'cexpo' : 2,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'helmet'
       }
     },
     'tp' : {
       'active' : 1,
       'sort' : 34,
       'name' : '钛钢镀饰',
       'nickname' : 'TP',
       'bonus' : ' 盔甲加成',
       'max' : -1,
       'effect' : .08,
       'gmax' : .32,
       'grate' : .00015,
       'gexpo' : .5,
       'ad' : .5,
       'ccoef' : .65,
       'cexpo' : 2,
       'type' : 'multiply',
       'expo' : {
         'flat' : 'gold'
       }
     },
     'as' : {
       'active' : 1,
       'sort' : 35,
       'name' : '紫晶之杖',
       'nickname' : 'ASt',
       'bonus' : ' 劈砍装备加成',
       'max' : -1,
       'effect' : .08,
       'gmax' : .32,
       'grate' : .00015,
       'gexpo' : .5,
       'ad' : .5,
       'ccoef' : .65,
       'cexpo' : 2,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'companion'
       }
     },
     'ig' : {
       'active' : 1,
       'sort' : 36,
       'name' : '入侵者的海姆达尔之角',
       'nickname' : 'IG',
       'bonus' : ' 所有主动技能效果',
       'max' : -1,
       'effect' : .02,
       'gmax' : .36,
       'grate' : .00018,
       'gexpo' : .5,
       'ad' : .2,
       'ccoef' : .6,
       'cexpo' : 1.8,
       'type' : 'multiply',
       'expo' : {
         'sum' : 'skill'
       }
     },
     'tm' : {
       'active' : 1,
       'sort' : 37,
       'name' : '巨人面具',
       'nickname' : 'TM',
       'bonus' : ' 天堂圣击伤害',
       'max' : -1,
       'effect' : .1,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .2,
       'ccoef' : .6,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'hs'
       }
     },
     'rt' : {
       'active' : 1,
       'sort' : 38,
       'name' : '皇室毒物',
       'nickname' : 'RT',
       'bonus' : ' 致命打击效果',
       'max' : -1,
       'effect' : .1,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .2,
       'ccoef' : .6,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'ds'
       }
     },
     'lp' : {
       'active' : 1,
       'sort' : 39,
       'name' : '工人垂饰',
       'nickname' : 'LP',
       'bonus' : ' 米达斯之手加成',
       'max' : -1,
       'effect' : .1,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .2,
       'ccoef' : .6,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'flat' : 'gold_phom'
       }
     },
     'bor' : {
       'active' : 1,
       'sort' : 40,
       'name' : '诸神黄昏使者',
       'nickname' : 'BoR',
       'bonus' : ' 火焰之剑伤害',
       'max' : -1,
       'effect' : .1,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .2,
       'ccoef' : .6,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'fs'
       }
     },
     'pof' : {
       'active' : 1,
       'sort' : 41,
       'name' : '预知羊皮纸',
       'nickname' : 'PoF',
       'bonus' : ' 战嚎伤害加成',
       'max' : -1,
       'effect' : .1,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .2,
       'ccoef' : .6,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'wc'
       }
     },
     'eoe' : {
       'active' : 1,
       'sort' : 42,
       'name' : '伊甸灵丹',
       'nickname' : 'EoE',
       'bonus' : ' 影分身伤害',
       'max' : -1,
       'effect' : .1,
       'gmax' : .4,
       'grate' : .0002,
       'gexpo' : .5,
       'ad' : .2,
       'ccoef' : .6,
       'cexpo' : 1.7,
       'type' : 'multiply',
       'expo' : {
         'reduct' : 'sc'
       }
     },
     'hoti' : {
       'active' : 1,
       'sort' : 43,
       'name' : '急速沙漏',
       'nickname' : 'HotI',
       'bonus' : ' 全主动技能冷却速率',
       'max' : 40,
       'effect' : -0.02,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : .8,
       'ccoef' : .5,
       'cexpo' : 2.6,
       'type' : 'pct',
       'expo' : {
         'sum' : 'skill'
       }
     },
     'pt' : {
       'active' : 1,
       'sort' : 44,
       'name' : '幻影时钟',
       'nickname' : 'PT',
       'bonus' : '秒 所有主动技能持续时间',
       'max' : 30,
       'effect' : 1,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : .8,
       'ccoef' : 1,
       'cexpo' : 3,
       'type' : 'add',
       'expo' : {
         'sum' : 'skill'
       }
     },
     'fs' : {
       'active' : 1,
       'sort' : 45,
       'name' : '禁忌卷轴',
       'nickname' : 'FS',
       'bonus' : '秒 致命打击持续时间',
       'max' : 30,
       'effect' : 2,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 1.5,
       'ccoef' : .6,
       'cexpo' : 2.4,
       'type' : 'add',
       'expo' : {
         'reduct' : 'ds'
       }
     },
     'rof' : {
       'active' : 1,
       'sort' : 46,
       'name' : '效忠指环',
       'nickname' : 'RoF',
       'bonus' : '秒 米达斯之手持续时间',
       'max' : 30,
       'effect' : 2,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 1.5,
       'ccoef' : .6,
       'cexpo' : 2.4,
       'type' : 'add',
       'expo' : {
         'flat' : 'gold_phom'
       }
     },
     'ga' : {
       'active' : 1,
       'sort' : 47,
       'name' : '冰川之斧',
       'nickname' : 'GA',
       'bonus' : '秒 火焰之剑持续时间',
       'max' : 30,
       'effect' : 2,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 1.5,
       'ccoef' : .6,
       'cexpo' : 2.4,
       'type' : 'add',
       'expo' : {
         'reduct' : 'fs'
       }
     },
     'a' : {
       'active' : 1,
       'sort' : 48,
       'name' : '神盾',
       'nickname' : 'A',
       'bonus' : '秒 战嚎持续时间',
       'max' : 30,
       'effect' : 2,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 1.5,
       'ccoef' : .6,
       'cexpo' : 2.4,
       'type' : 'add',
       'expo' : {
         'reduct' : 'wc'
       }
     },
     'sg' : {
       'active' : 1,
       'sort' : 49,
       'name' : '沼泽手套',
       'nickname' : 'SG',
       'bonus' : '秒 影分身术持续时间',
       'max' : 30,
       'effect' : 2,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 1.5,
       'ccoef' : .6,
       'cexpo' : 2.4,
       'type' : 'add',
       'expo' : {
         'reduct' : 'sc'
       }
     },
     'ip' : {
       'active' : 1,
       'sort' : 50,
       'name' : '无限摆锤',
       'nickname' : 'IP',
       'bonus' : ' 天堂圣击法力消耗',
       'max' : 20,
       'effect' : -1,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : .9,
       'ccoef' : .6,
       'cexpo' : 3,
       'type' : 'add',
       'expo' : {
         'reduct' : 'hs'
       }
     },
     'gok' : {
       'active' : 1,
       'sort' : 51,
       'name' : '大熊手套',
       'nickname' : 'GoK',
       'bonus' : ' 致命打击法力消耗',
       'max' : 30,
       'effect' : -1,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : .8,
       'ccoef' : .6,
       'cexpo' : 3,
       'type' : 'add',
       'expo' : {
         'reduct' : 'ds'
       }
     },
     'ts' : {
       'active' : 1,
       'sort' : 52,
       'name' : '巨人之矛',
       'nickname' : 'TS',
       'bonus' : ' 米达斯之手法力消耗',
       'max' : 40,
       'effect' : -1,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : .8,
       'ccoef' : .6,
       'cexpo' : 3,
       'type' : 'add',
       'expo' : {
         'flat' : 'gold_phom'
       }
     },
     'os' : {
       'active' : 1,
       'sort' : 53,
       'name' : '橡木杖',
       'nickname' : 'OS',
       'bonus' : ' 火焰之剑法力消耗',
       'max' : 30,
       'effect' : -1,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : .8,
       'ccoef' : .6,
       'cexpo' : 3,
       'type' : 'add',
       'expo' : {
         'reduct' : 'fs'
       }
     },
     'tac' : {
       'active' : 1,
       'sort' : 54,
       'name' : '奥秘斗篷',
       'nickname' : 'TAC',
       'bonus' : ' 战嚎法力消耗',
       'max' : 40,
       'effect' : -1,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : .8,
       'ccoef' : .6,
       'cexpo' : 3,
       'type' : 'add',
       'expo' : {
         'reduct' : 'wc'
       }
     },
     'ho' : {
       'active' : 1,
       'sort' : 55,
       'name' : '猎人药膏',
       'nickname' : 'HO',
       'bonus' : ' 影分身术法力消耗',
       'max' : 40,
       'effect' : -1,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : .8,
       'ccoef' : .6,
       'cexpo' : 3,
       'type' : 'add',
       'expo' : {
         'reduct' : 'sc'
       }
     },
     'ae' : {
       'active' : 1,
       'sort' : 56,
       'name' : '仙馔密酒',
       'nickname' : 'AE',
       'bonus' : ' 法力池上限',
       'max' : 40,
       'effect' : 2,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : .8,
       'ccoef' : .6,
       'cexpo' : 3,
       'type' : 'add',
       'expo' : {
         'sum' : 'skill'
       }
     },
     'ms' : {
       'active' : 1,
       'sort' : 57,
       'name' : '神秘权杖',
       'nickname' : 'MS',
       'bonus' : ' 法力回复',
       'max' : 40,
       'effect' : .075,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 2,
       'ccoef' : .5,
       'cexpo' : 2.6,
       'type' : 'add',
       'expo' : {
         'sum' : 'skill'
       }
     },
     'mbos' : {
       'active' : 1,
       'sort' : 58,
       'name' : '千头的神秘豆',
       'nickname' : 'MBoS',
       'bonus' : ' 法力百分比退还',
       'max' : 40,
       'effect' : .0025,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 2,
       'ccoef' : .5,
       'cexpo' : 2.6,
       'type' : 'pct',
       'expo' : {
         'sum' : 'skill'
       }
     },
     'eof' : {
       'active' : 1,
       'sort' : 59,
       'name' : '幸运之卵',
       'nickname' : 'EoF',
       'bonus' : ' 宝箱兽机率',
       'max' : 40,
       'effect' : .005,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 2,
       'ccoef' : 1.4,
       'cexpo' : 3,
       'type' : 'pct',
       'expo' : {
         'gold' : [
           'coc',
           'phom',
           'all',
           'splash',
           'active'
         ]
       }
     },
     'dc' : {
       'active' : 1,
       'sort' : 60,
       'name' : '圣杯',
       'nickname' : 'DC',
       'bonus' : ' 10倍黄金机率',
       'max' : 50,
       'effect' : .01,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 1,
       'ccoef' : .8,
       'cexpo' : 2.6,
       'type' : 'pct',
       'expo' : {
         'gold' : [
           'phom',
           'all',
           'active'
         ]
       }
     },
     'is' : {
       'active' : 1,
       'sort' : 61,
       'name' : '入侵者之盾',
       'nickname' : 'IS',
       'bonus' : ' 多重仙女机率',
       'max' : 50,
       'effect' : 0.005,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 1.6,
       'ccoef' : .5,
       'cexpo' : 2.1,
       'type' : 'pct',
       'expo' : {
         'flat' : 'active'
       }
     },
     'aom' : {
       'active' : 1,
       'sort' : 62,
       'name' : '死亡之斧',
       'nickname' : 'AoM',
       'bonus' : ' 暴击几率',
       'max' : 40,
       'effect' : 0.005,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 3,
       'ccoef' : .8,
       'cexpo' : 2.5,
       'type' : 'pct',
       'expo' : {
         'reduct' : 'crit'
       }
     },
     'eotk' : {
       'active' : 1,
       'sort' : 63,
       'name' : '狐仙精华',
       'nickname' : 'EotK',
       'bonus' : ' 多重重生几率',
       'max' : 40,
       'effect' : .005,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 3,
       'ccoef' : .8,
       'cexpo' : 2.5,
       'type' : 'pct',
       'expo' : {
         'flat' : 'inactive'
       }
     },
     'boh' : {
       'active' : 1,
       'sort' : 64,
       'name' : '爱马仕之靴',
       'nickname' : 'BoH',
       'bonus' : ' 跳关怪几率',
       'max' : 40,
       'effect' : .001,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 3,
       'ccoef' : .8,
       'cexpo' : 2.5,
       'type' : 'pct',
       'expo' : {
         'flat' : 'dmg'
       }
     },
     'lfoa' : {
       'active' : 1,
       'sort' : 65,
       'name' : '铝登霄的幸运足',
       'nickname' : 'LFoA',
       'bonus' : ' 所有概率加成',
       'max' : 40,
       'effect' : .0025,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 2,
       'ccoef' : .5,
       'cexpo' : 2.6,
       'type' : 'multiply',
       'expo' : {
         'flat' : 'dmg'
       }
     },
     'lkm' : {
       'active' : 1,
       'sort' : 66,
       'name' : '失落的王者面具',
       'nickname' : 'LKM',
       'bonus' : ' 全升级费用',
       'max' : 40,
       'effect' : -.02,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : .8,
       'ccoef' : .5,
       'cexpo' : 3,
       'type' : 'pct',
       'expo' : {
         'flat' : 'dmg'
       }
     },
     'sor' : {
       'active' : 1,
       'sort' : 67,
       'name' : '光辉之杖',
       'nickname' : 'SoR',
       'bonus' : ' 英雄升级花费',
       'max' : 40,
       'effect' : -.02,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : .8,
       'ccoef' : .5,
       'cexpo' : 2.6,
       'type' : 'pct',
       'expo' : {
         'reduct' : 'hero'
       }
     },
     'tms' : {
       'active' : 1,
       'sort' : 68,
       'name' : '大师之剑',
       'nickname' : 'TMS',
       'bonus' : ' 剑圣升级花费',
       'max' : 40,
       'effect' : .0001,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 2,
       'ccoef' : .5,
       'cexpo' : 2.6,
       'type' : 'pct',
       'expo' : {
         'reduct' : 'tap'
       }
     },
     'as2' : {
       'active' : 1,
       'sort' : 69,
       'name' : '亚兰之矛',
       'nickname' : 'ASp',
       'bonus' : ' 巨人生命值',
       'max' : 40,
       'effect' : -.02,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 2,
       'ccoef' : .5,
       'cexpo' : 2.6,
       'type' : 'pct',
       'expo' : {
         'flat' : 'dmg'
       }
     },
     'wod' : {
       'active' : 1,
       'sort' : 70,
       'name' : '暗黑守卫',
       'nickname' : 'WoD',
       'bonus' : '秒 魔王计时条',
       'max' : 60,
       'effect' : 1,
       'gmax' : 0,
       'grate' : 0,
       'gexpo' : 1,
       'ad' : 2,
       'ccoef' : .5,
       'cexpo' : 2.6,
       'type' : 'add',
       'expo' : {
         'flat' : 'dmg'
       }
     }
   }
 };
 
 var artifact_costs = {
   '0' : -1,
   '1' : 1,
   '2' : 3,
   '3' : 6,
   '4' : 11,
   '5' : 19,
   '6' : 30,
   '7' : 46,
   '8' : 69,
   '9' : 102,
   '10' : 148,
   '11' : 214,
   '12' : 306,
   '13' : 434,
   '14' : 613,
   '15' : 861,
   '16' : 1203,
   '17' : 1675,
   '18' : 2323,
   '19' : 3212,
   '20' : 4430,
   '21' : 6094,
   '22' : 8363,
   '23' : 11454,
   '24' : 15657,
   '25' : 21365,
   '26' : 29108,
   '27' : 39599,
   '28' : 53796,
   '29' : 72990,
   '30' : 98914,
   '31' : 133897,
   '32' : 181063,
   '33' : 244605,
   '34' : 330143,
   '35' : 445208,
   '36' : 599886,
   '37' : 807680,
   '38' : 1086657,
   '39' : 1460982,
   '40' : 1962961,
   '41' : 2801512,
   '42' : 4271796,
   '43' : 6546742,
   '44' : 10084102,
   '45' : 15611565,
   '46' : 24291381,
   '47' : 37988598,
   '48' : 59710114,
   '49' : 94326541,
   '50' : 149764436,
   '51' : 238984254,
   '52' : 383276658,
   '53' : 617780678,
   '54' : 1000762985,
   '55' : 1629292101,
   '56' : 2665833882,
   '57' : 4383580899,
   '58' : 7244059100,
   '59' : 12030591779,
   '60' : 20078853673,
   '61' : 33676929221,
   '62' : 56762601881,
   '63' : 96144140647,
   '64' : 163647145909,
   '65' : 279906771691,
   '66' : 3840000000000,
   '67' : 53170000000000,
   '68' : 738330000000000,
   '69' : 10300000000000000,
   '70' : 144000000000000000,
   '71' : -1
 };
 
 // x = 1.4067499999999975
 // x += 0.00395
 // a = 66
 // a * Math.pow(x, a++)
 
 var tiers = {
   '1' : 0,
   '2' : 3,
   '3' : 20,
   '4' : 50
 }
 
 var skills = {
   'totals' : {
     'SP' : 0,
     'red' : 0,
     'yellow' : 0,
     'blue' : 0,
     'green' : 0
   },
   'data' : {
     'kv' : {
       'active' : 1,
       'sort' : 1,
       'name' : '骑士之勇',
       'nickname' : 'R1',
       'branch' : 'red',
       'bonus' : ' 点击伤害',
       'bonus2' : -1,
       'bonus3' : -1,
       'tier' : 1,
       'prereq' : -1,
       'max' : 20,
       'type' : 'multiply',
       'type2' : -1,
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 1.2, 'bonus2' : 0, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 1.6, 'bonus2' : 0, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : 2.2, 'bonus2' : 0, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : 3.3, 'bonus2' : 0, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 5, 'bonus2' : 0, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : 7.4, 'bonus2' : 0, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : 11.8, 'bonus2' : 0, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 20.5, 'bonus2' : 0, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : 35.5, 'bonus2' : 0, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : 66.1, 'bonus2' : 0, 'bonus3' : 0 },
         '11' : { 'cost' : 7, 'bonus' : 132, 'bonus2' : 0, 'bonus3' : 0 },
         '12' : { 'cost' : 8, 'bonus' : 282.4, 'bonus2' : 0, 'bonus3' : 0 },
         '13' : { 'cost' : 9, 'bonus' : 644.7, 'bonus2' : 0, 'bonus3' : 0 },
         '14' : { 'cost' : 11, 'bonus' : 1670, 'bonus2' : 0, 'bonus3' : 0 },
         '15' : { 'cost' : 12, 'bonus' : 4580, 'bonus2' : 0, 'bonus3' : 0 },
         '16' : { 'cost' : 14, 'bonus' : 14100, 'bonus2' : 0, 'bonus3' : 0 },
         '17' : { 'cost' : 16, 'bonus' : 48400, 'bonus2' : 0, 'bonus3' : 0 },
         '18' : { 'cost' : 19, 'bonus' : 193000, 'bonus2' : 0, 'bonus3' : 0 },
         '19' : { 'cost' : 22, 'bonus' : 889000, 'bonus2' : 0, 'bonus3' : 0 },
         '20' : { 'cost' : 25, 'bonus' : 4670000, 'bonus2' : 0, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'tap'
       }
     },
     'cho' : {
       'active' : 1,
       'sort' : 2,
       'name' : '骑士勋章',
       'nickname' : 'R2_1',
       'branch' : 'red',
       'bonus' : ' 点击伤害来自英雄伤害',
       'bonus2' : -1,
       'bonus3' : -1,
       'tier' : 2,
       'prereq' : 'kv',
       'max' : 20,
       'type' : 'pct_pos',
       'type2' : -1,
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : .0004, 'bonus2' : 0, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : .0006, 'bonus2' : 0, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : .0009, 'bonus2' : 0, 'bonus3' : 0  },
         '4' : { 'cost' : 3, 'bonus' : .0015, 'bonus2' : 0, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : .0025, 'bonus2' : 0, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : .004, 'bonus2' : 0, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : .0067, 'bonus2' : 0, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : .0116, 'bonus2' : 0, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : .0204, 'bonus2' : 0, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : .0371, 'bonus2' : 0, 'bonus3' : 0 },
         '11' : { 'cost' : 7, 'bonus' : .0701, 'bonus2' : 0, 'bonus3' : 0 },
         '12' : { 'cost' : 8, 'bonus' : .1373, 'bonus2' : 0, 'bonus3' : 0 },
         '13' : { 'cost' : 9, 'bonus' : .2788, 'bonus2' : 0, 'bonus3' : 0 },
         '14' : { 'cost' : 11, 'bonus' : .6049, 'bonus2' : 0, 'bonus3' : 0 },
         '15' : { 'cost' : 12, 'bonus' : 1.36, 'bonus2' : 0, 'bonus3' : 0 },
         '16' : { 'cost' : 14, 'bonus' : 3.23, 'bonus2' : 0, 'bonus3' : 0 },
         '17' : { 'cost' : 16, 'bonus' : 8.13, 'bonus2' : 0, 'bonus3' : 0 },
         '18' : { 'cost' : 19, 'bonus' : 22.2, 'bonus2' : 0, 'bonus3' : 0 },
         '19' : { 'cost' : 22, 'bonus' : 65.2, 'bonus2' : 0, 'bonus3' : 0 },
         '20' : { 'cost' : 25, 'bonus' : 205.5, 'bonus2' : 0, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'tap'
       }
     },
     'pe' : {
       'active' : 1,
       'sort' : 3,
       'name' : '宠物进化',
       'nickname' : 'R2_2',
       'branch' : 'red',
       'bonus' : ' 宠物伤害',
       'bonus2' : ' 点击需求以发动宠物攻击',
       'bonus3' : -1,
       'tier' : 2,
       'prereq' : 'kv',
       'max' : 20,
       'type' : 'multiply',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 1.5, 'bonus2' : 0, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 2.1, 'bonus2' : -1, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : 2.9, 'bonus2' : -1, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : 4.4, 'bonus2' : -2, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 6.7, 'bonus2' : -2, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : 10.2, 'bonus2' : -3, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : 16.9, 'bonus2' : -3, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 30.4, 'bonus2' : -4, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : 54.6, 'bonus2' : -4, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : 106.2, 'bonus2' : -5, 'bonus3' : 0 },
         '11' : { 'cost' : 7, 'bonus' : 222.5, 'bonus2' : -5, 'bonus3' : 0 },
         '12' : { 'cost' : 8, 'bonus' : 501.6, 'bonus2' : -6, 'bonus3' : 0 },
         '13' : { 'cost' : 9, 'bonus' : 1210, 'bonus2' : -6, 'bonus3' : 0 },
         '14' : { 'cost' : 11, 'bonus' : 3350, 'bonus2' : -7, 'bonus3' : 0 },
         '15' : { 'cost' : 12, 'bonus' : 9860, 'bonus2' : -7, 'bonus3' : 0 },
         '16' : { 'cost' : 14, 'bonus' : 9860, 'bonus2' : -8, 'bonus3' : 0 },
         '17' : { 'cost' : 16, 'bonus' : 122000, 'bonus2' : -8, 'bonus3' : 0 },
         '18' : { 'cost' : 19, 'bonus' : 534000, 'bonus2' : -9, 'bonus3' : 0 },
         '19' : { 'cost' : 22, 'bonus' : 2710000, 'bonus2' : -9, 'bonus3' : 0 },
         '20' : { 'cost' : 25, 'bonus' : 15800000, 'bonus2' : -10, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'pet'
       }
     },
     'phom' : {
       'active' : 1,
       'sort' : 4,
       'name' : '米达斯之心',
       'branch' : 'red',
       'nickname' : 'R2_3',
       'bonus' : ' 米达斯之手黄金',
       'bonus2' : '秒钟 冷却',
       'bonus3' : -1,
       'tier' : 2,
       'prereq' : 'kv',
       'max' : 20,
       'type' : 'add_skill',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 4, 'bonus2' : 0, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 11.2, 'bonus2' : 1, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : 24.3, 'bonus2' : 2, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : 52.1, 'bonus2' : 3, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 107, 'bonus2' : 4, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : 215.4, 'bonus2' : 5, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : 467.5, 'bonus2' : 6, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 1100, 'bonus2' : 7, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : 2560, 'bonus2' : 8, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : 6480, 'bonus2' : 9, 'bonus3' : 0 },
         '11' : { 'cost' : 7, 'bonus' : 17700, 'bonus2' : 10, 'bonus3' : 0 },
         '12' : { 'cost' : 8, 'bonus' : 51900, 'bonus2' : 11, 'bonus3' : 0 },
         '13' : { 'cost' : 9, 'bonus' : 164000, 'bonus2' : 12, 'bonus3' : 0 },
         '14' : { 'cost' : 11, 'bonus' : 592000, 'bonus2' : 13, 'bonus3' : 0 },
         '15' : { 'cost' : 12, 'bonus' : 2280000, 'bonus2' : 14, 'bonus3' : 0 },
         '16' : { 'cost' : 14, 'bonus' : 9980000, 'bonus2' : 15, 'bonus3' : 0 },
         '17' : { 'cost' : 16, 'bonus' : 49100000, 'bonus2' : 16, 'bonus3' : 0 },
         '18' : { 'cost' : 19, 'bonus' : 286000000, 'bonus2' : 17, 'bonus3' : 0 },
         '19' : { 'cost' : 22, 'bonus' : 1940000000, 'bonus2' : 18, 'bonus3' : 0 },
         '20' : { 'cost' : 25, 'bonus' : 15200000000, 'bonus2' : 20, 'bonus3' : 0 }
       },
       'expo' : {
         'gold' : [
           'phom',
           'all',
         ]
       }
     },
     'cs' : {
       'active' : 1,
       'sort' : 5,
       'name' : '劈砍',
       'nickname' : 'R3_1',
       'branch' : 'red',
       'bonus' : ' 最高暴击伤害',
       'bonus2' : ' 暴击几率',
       'bonus3' : -1,
       'tier' : 3,
       'prereq' : 'cho',
       'max' : 20,
       'type' : 'multiply',
       'type2' : 'pct_pos',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 2, 'bonus' : 1.8, 'bonus2' : -.01, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 2.8, 'bonus2' : -.02, 'bonus3' : 0 },
         '3' : { 'cost' : 3, 'bonus' : 4.4, 'bonus2' : -.03, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : 7.2, 'bonus2' : -.04, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 12.3, 'bonus2' : -.05, 'bonus3' : 0 },
         '6' : { 'cost' : 4, 'bonus' : 22.1, 'bonus2' : -.06, 'bonus3' : 0 },
         '7' : { 'cost' : 5, 'bonus' : 41.8, 'bonus2' : -.07, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 83.9, 'bonus2' : -.08, 'bonus3' : 0 },
         '9' : {  'cost' : 6, 'bonus' : 180.1, 'bonus2' : -.09, 'bonus3' : 0 },
         '10' : { 'cost' : 7, 'bonus' : 415.9, 'bonus2' : -.1, 'bonus3' : 0 },
         '11' : { 'cost' : 8, 'bonus' : 1040, 'bonus2' : -.11, 'bonus3' : 0 },
         '12' : { 'cost' : 9, 'bonus' : 2860, 'bonus2' : -.12, 'bonus3' : 0 },
         '13' : { 'cost' : 11, 'bonus' : 8690, 'bonus2' : -.13, 'bonus3' : 0 },
         '14' : { 'cost' : 12, 'bonus' : 29500, 'bonus2' : -.14, 'bonus3' : 0 },
         '15' : { 'cost' : 14, 'bonus' : 113000, 'bonus2' : -.15, 'bonus3' : 0 },
         '16' : { 'cost' : 16, 'bonus' : 491000, 'bonus2' : -.16, 'bonus3' : 0 },
         '17' : { 'cost' : 19, 'bonus' : 2470000, 'bonus2' : -.17, 'bonus3' : 0 },
         '18' : { 'cost' : 22, 'bonus' : 14500000, 'bonus2' : -.18, 'bonus3' : 0 },
         '19' : { 'cost' : 25, 'bonus' : 99900000, 'bonus2' : -.19, 'bonus3' : 0 },
         '20' : { 'cost' : 28, 'bonus' : 823000000, 'bonus2' : -.2, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'crit_sc'
       }
     },
     'si' : {
       'active' : 1,
       'sort' : 6,
       'name' : '召唤地狱火',
       'nickname' : 'R3_2',
       'branch' : 'red',
       'bonus' : ' 火焰之剑伤害',
       'bonus2' : -1,
       'bonus3' : -1,
       'tier' : 3,
       'prereq' : 'pe',
       'max' : 20,
       'type' : 'multiply',
       'type2' : -1,
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 2, 'bonus' : 1.6, 'bonus2' : 0, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 2.3, 'bonus2' : 0, 'bonus3' : 0 },
         '3' : { 'cost' : 3, 'bonus' : 3.7, 'bonus2' : 0, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : 5.9, 'bonus2' : 0, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 9.3, 'bonus2' : 0, 'bonus3' : 0 },
         '6' : { 'cost' : 4, 'bonus' : 16.2, 'bonus2' : 0, 'bonus3' : 0 },
         '7' : { 'cost' : 5, 'bonus' : 30.5, 'bonus2' : 0, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 57.4, 'bonus2' : 0, 'bonus3' : 0 },
         '9' : {  'cost' : 6, 'bonus' : 117.1, 'bonus2' : 0, 'bonus3' : 0 },
         '10' : { 'cost' : 7, 'bonus' : 258, 'bonus2' : 0, 'bonus3' : 0 },
         '11' : { 'cost' : 8, 'bonus' : 612.5, 'bonus2' : 0, 'bonus3' : 0 },
         '12' : { 'cost' : 9, 'bonus' : 1560, 'bonus2' : 0, 'bonus3' : 0 },
         '13' : { 'cost' : 11, 'bonus' : 4580, 'bonus2' : 0, 'bonus3' : 0 },
         '14' : { 'cost' : 12, 'bonus' : 14300, 'bonus2' : 0, 'bonus3' : 0 },
         '15' : { 'cost' : 14, 'bonus' : 50700, 'bonus2' : 0, 'bonus3' : 0 },
         '16' : { 'cost' : 16, 'bonus' : 203000, 'bonus2' : 0, 'bonus3' : 0 },
         '17' : { 'cost' : 19, 'bonus' : 957000, 'bonus2' : 0, 'bonus3' : 0 },
         '18' : { 'cost' : 22, 'bonus' : 5270000, 'bonus2' : 0, 'bonus3' : 0 },
         '19' : { 'cost' : 25, 'bonus' : 33600000, 'bonus2' : 0, 'bonus3' : 0 },
         '20' : { 'cost' : 28, 'bonus' : 246000000, 'bonus2' : 0, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'fs'
       }
     },
     'lbu' : {
       'active' : 1,
       'sort' : 7,
       'name' : '闪电爆发',
       'nickname' : 'R3_3',
       'branch' : 'red',
       'bonus' : ' 宠物伤害每次闪电爆发',
       'bonus2' : ' 最大闪电爆发攻击次数',
       'bonus3' : -1,
       'tier' : 3,
       'prereq' : 'phom',
       'max' : 20,
       'type' : 'multiply',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 2, 'bonus' : 3, 'bonus2' : 2, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 7.6, 'bonus2' : 4, 'bonus3' : 0 },
         '3' : { 'cost' : 3, 'bonus' : 15.5, 'bonus2' : 6, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : 28.6, 'bonus2' : 8, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 50.1, 'bonus2' : 10, 'bonus3' : 0 },
         '6' : { 'cost' : 4, 'bonus' : 92, 'bonus2' : 12, 'bonus3' : 0 },
         '7' : { 'cost' : 5, 'bonus' : 178.4, 'bonus2' : 14, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 343.1, 'bonus2' : 16, 'bonus3' : 0 },
         '9' : {  'cost' : 6, 'bonus' : 703.8, 'bonus2' : 18, 'bonus3' : 0 },
         '10' : { 'cost' : 7, 'bonus' : 1540, 'bonus2' : 20, 'bonus3' : 0 },
         '11' : { 'cost' : 8, 'bonus' : 3590, 'bonus2' : 22, 'bonus3' : 0 },
         '12' : { 'cost' : 9, 'bonus' : 8900, 'bonus2' : 24, 'bonus3' : 0 },
         '13' : { 'cost' : 11, 'bonus' : 24900, 'bonus2' : 27, 'bonus3' : 0 },
         '14' : { 'cost' : 12, 'bonus' : 73700, 'bonus2' : 30, 'bonus3' : 0 },
         '15' : { 'cost' : 14, 'bonus' : 244000, 'bonus2' : 33, 'bonus3' : 0 },
         '16' : { 'cost' : 16, 'bonus' : 896000, 'bonus2' : 36, 'bonus3' : 0 },
         '17' : { 'cost' : 19, 'bonus' : 3820000, 'bonus2' : 39, 'bonus3' : 0 },
         '18' : { 'cost' : 22, 'bonus' : 18700000, 'bonus2' : 42, 'bonus3' : 0 },
         '19' : { 'cost' : 25, 'bonus' : 104000000, 'bonus2' : 46, 'bonus3' : 0 },
         '20' : { 'cost' : 28, 'bonus' : 656000000, 'bonus2' : 50, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'pet'
       }
     },
     'bf' : {
       'active' : 1,
       'sort' : 8,
       'name' : '野蛮之怒',
       'nickname' : 'R4_1',
       'branch' : 'red',
       'bonus' : ' 点击伤害',
       'bonus2' : ' 每秒点击加成',
       'bonus3' : -1,
       'tier' : 4,
       'prereq' : 'cs',
       'max' : 12,
       'type' : 'multiply',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 3, 'bonus' : 2.5, 'bonus2' : 1, 'bonus3' : 0 },
         '2' : { 'cost' : 4, 'bonus' : 6.4, 'bonus2' : 2, 'bonus3' : 0 },
         '3' : { 'cost' : 5, 'bonus' : 18.6, 'bonus2' : 3, 'bonus3' : 0 },
         '4' : { 'cost' : 7, 'bonus' : 67.2, 'bonus2' : 4, 'bonus3' : 0 },
         '5' : { 'cost' : 9, 'bonus' : 298, 'bonus2' : 5, 'bonus3' : 0 },
         '6' : { 'cost' : 12, 'bonus' : 1750, 'bonus2' : 6, 'bonus3' : 0 },
         '7' : { 'cost' : 16, 'bonus' : 14200, 'bonus2' : 8, 'bonus3' : 0 },
         '8' : { 'cost' : 21, 'bonus' : 166000,  'bonus2' : 10, 'bonus3' : 0 },
         '9' : {  'cost' : 27, 'bonus' : 2810000, 'bonus2' : 12, 'bonus3' : 0 },
         '10' : { 'cost' : 35, 'bonus' : 72900000, 'bonus2' : 14, 'bonus3' : 0 },
         '11' : { 'cost' : 46, 'bonus' : 3090000000, 'bonus2' : 17, 'bonus3' : 0 },
         '12' : { 'cost' : 60, 'bonus' : 218000000000, 'bonus2' : 20, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'tap'
       }
     },
     'fz' : {
       'active' : 1,
       'sort' : 9,
       'name' : '闪电穿梭',
       'nickname' : 'R4_3',
       'branch' : 'red',
       'bonus' : ' 每个邮编序列的宠物伤害',
       'bonus2' : '秒钟 冷却',
       'bonus3' : -1,
       'tier' : 4,
       'prereq' : 'lbu',
       'max' : 12,
       'type' : 'multiply',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 3, 'bonus' : 1, 'bonus2' : 0, 'bonus3' : 0 },
         '2' : { 'cost' : 4, 'bonus' : 2.6, 'bonus2' : .5, 'bonus3' : 0 },
         '3' : { 'cost' : 5, 'bonus' : 7.3, 'bonus2' : 1, 'bonus3' : 0 },
         '4' : { 'cost' : 7, 'bonus' : 26.3, 'bonus2' : 2, 'bonus3' : 0 },
         '5' : { 'cost' : 9, 'bonus' : 115.4, 'bonus2' : 3, 'bonus3' : 0 },
         '6' : { 'cost' : 12, 'bonus' : 670.1, 'bonus2' : 4, 'bonus3' : 0 },
         '7' : { 'cost' : 16, 'bonus' : 5420, 'bonus2' : 5, 'bonus3' : 0 },
         '8' : { 'cost' : 21, 'bonus' : 63100, 'bonus2' : 6, 'bonus3' : 0 },
         '9' : {  'cost' : 27, 'bonus' : 1070000, 'bonus2' : 7, 'bonus3' : 0 },
         '10' : { 'cost' : 35, 'bonus' : 28200000, 'bonus2' : 8, 'bonus3' : 0 },
         '11' : { 'cost' : 46, 'bonus' : 1220000000, 'bonus2' : 9, 'bonus3' : 0 },
         '12' : { 'cost' : 60, 'bonus' : 89000000000, 'bonus2' : 10, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'pet'
       }
     },
     'mc' : {
       'active' : 1,
       'sort' : 10,
       'name' : '指挥官',
       'nickname' : 'Y1',
       'branch' : 'yellow',
       'bonus' : ' 全部英雄伤害',
       'bonus2' : -1,
       'bonus3' : -1,
       'tier' : 1,
       'prereq' : -1,
       'max' : 20,
       'type' : 'multiply',
       'type2' : -1,
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 1.2, 'bonus2' : 0, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 1.7, 'bonus2' : 0, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : 2.3, 'bonus2' : 0, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : 3.4, 'bonus2' : 0, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 5.2, 'bonus2' : 0, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : 7.8, 'bonus2' : 0, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : 12.7, 'bonus2' : 0, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 22.5, 'bonus2' : 0, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : 39.7, 'bonus2' : 0, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : 75.8, 'bonus2' : 0, 'bonus3' : 0 },
         '11' : { 'cost' : 7, 'bonus' : 155.8, 'bonus2' : 0, 'bonus3' : 0 },
         '12' : { 'cost' : 8, 'bonus' : 343.6, 'bonus2' : 0, 'bonus3' : 0 },
         '13' : { 'cost' : 9, 'bonus' : 811.8, 'bonus2' : 0, 'bonus3' : 0 },
         '14' : { 'cost' : 11, 'bonus' : 2190, 'bonus2' : 0, 'bonus3' : 0 },
         '15' : { 'cost' : 12, 'bonus' : 6280, 'bonus2' : 0, 'bonus3' : 0 },
         '16' : { 'cost' : 14, 'bonus' : 20300, 'bonus2' : 0, 'bonus3' : 0 },
         '17' : { 'cost' : 16, 'bonus' : 73600, 'bonus2' : 0, 'bonus3' : 0 },
         '18' : { 'cost' : 19, 'bonus' : 313000, 'bonus2' : 0, 'bonus3' : 0 },
         '19' : { 'cost' : 22, 'bonus' : 1540000, 'bonus2' : 0, 'bonus3' : 0 },
         '20' : { 'cost' : 25, 'bonus' : 8730000, 'bonus2' : 0, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'hero'
       }
     },
     'sow' : {
       'active' : 1,
       'sort' : 11,
       'name' : '战利品',
       'nickname' : 'Y2_1',
       'branch' : 'yellow',
       'bonus' : ' 宝箱兽黄金',
       'bonus2' : ' 宝箱兽几率',
       'bonus3' : -1,
       'tier' : 2,
       'prereq' : 'mc',
       'max' : 20,
       'type' : 'multiply',
       'type2' : 'pct_pos',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 1.8, 'bonus2' : .01, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 3.3, 'bonus2' : .02, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : 6.2, 'bonus2' : .03, 'bonus3' : 0  },
         '4' : { 'cost' : 3, 'bonus' : 12.7, 'bonus2' : .04, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 25.8, 'bonus2' : .05, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : 52.7, 'bonus2' : .06, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : 117.7, 'bonus2' : .07, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 286.8, 'bonus2' : .08, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : 698.9, 'bonus2' : .09, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : 1850, 'bonus2' : .1, 'bonus3' : 0 },
         '11' : { 'cost' : 7, 'bonus' : 5330, 'bonus2' : .11, 'bonus3' : 0 },
         '12' : { 'cost' : 8, 'bonus' : 16600, 'bonus2' : .12, 'bonus3' : 0 },
         '13' : { 'cost' : 9, 'bonus' : 55700, 'bonus2' : .13, 'bonus3' : 0 },
         '14' : { 'cost' : 11, 'bonus' : 216000, 'bonus2' : .14, 'bonus3' : 0 },
         '15' : { 'cost' : 12, 'bonus' : 900000, 'bonus2' : .15, 'bonus3' : 0 },
         '16' : { 'cost' : 14, 'bonus' : 4280000, 'bonus2' : .16, 'bonus3' : 0 },
         '17' : { 'cost' : 16, 'bonus' : 23100000, 'bonus2' : .17, 'bonus3' : 0 },
         '18' : { 'cost' : 19, 'bonus' : 149000000, 'bonus2' : .18, 'bonus3' : 0 },
         '19' : { 'cost' : 22, 'bonus' : 1130000000, 'bonus2' : .19, 'bonus3' : 0 },
         '20' : { 'cost' : 25, 'bonus' : 10100000000, 'bonus2' : .2, 'bonus3' : 0 }
       },
       'expo' : {
         'gold' : [
           'coc',
           'fairy',
           'phom',
           'partial_splash',
           'partial_inactive'
         ]
       }
     },
     'hm' : {
       'active' : 1,
       'sort' : 12,
       'name' : '英雄王者',
       'nickname' : 'Y2_2',
       'branch' : 'yellow',
       'bonus' : ' 战壕伤害',
       'bonus2' : ' 被激励的英雄数量',
       'bonus3' : -1,
       'tier' : 2,
       'prereq' : 'mc',
       'max' : 20,
       'type' : 'multiply',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 1.5, 'bonus2' : 1, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 2, 'bonus2' : 2, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : 2.8, 'bonus2' : 3, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : 4.2, 'bonus2' : 4, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 6.2, 'bonus2' : 5, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : 9.3, 'bonus2' : 6, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : 15.1, 'bonus2' : 7, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 26.8, 'bonus2' : 8, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : 47.7, 'bonus2' : 9, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : 91.8, 'bonus2' : 10, 'bonus3' : 0 },
         '11' : { 'cost' : 7, 'bonus' : 191.5, 'bonus2' : 11, 'bonus3' : 0 },
         '12' : { 'cost' : 8, 'bonus' : 430.9, 'bonus2' : 12, 'bonus3' : 0 },
         '13' : { 'cost' : 9, 'bonus' : 1040, 'bonus2' : 13, 'bonus3' : 0 },
         '14' : { 'cost' : 11, 'bonus' : 2910, 'bonus2' : 14, 'bonus3' : 0 },
         '15' : { 'cost' : 12, 'bonus' : 8690, 'bonus2' : 15, 'bonus3' : 0 },
         '16' : { 'cost' : 14, 'bonus' : 29500, 'bonus2' : 16, 'bonus3' : 0 },
         '17' : { 'cost' : 16, 'bonus' : 113000, 'bonus2' : 17, 'bonus3' : 0 },
         '18' : { 'cost' : 19, 'bonus' : 513000, 'bonus2' : 18, 'bonus3' : 0 },
         '19' : { 'cost' : 22, 'bonus' : 2730000, 'bonus2' : 19, 'bonus3' : 0 },
         '20' : { 'cost' : 25, 'bonus' : 16900000, 'bonus2' : 20, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'wc'
       }
     },
     'aas' : {
       'active' : 1,
       'sort' : 13,
       'name' : '空袭',
       'nickname' : 'Y2_3',
       'branch' : 'yellow',
       'bonus' : ' 基于部落的伤害',
       'bonus2' : ' 最大溅射数量',
       'bonus3' : -1,
       'tier' : 2,
       'prereq' : 'mc',
       'max' : 20,
       'type' : 'multiply',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 1.5, 'bonus2' : 1, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 2, 'bonus2' : 2, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : 2.6, 'bonus2' : 3, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : 3.8, 'bonus2' : 4, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 5.4, 'bonus2' : 5, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : 7.8, 'bonus2' : 6, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : 12.2, 'bonus2' : 7, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 20.6, 'bonus2' : 8, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : 34.8, 'bonus2' : 9, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : 63.5, 'bonus2' : 10, 'bonus3' : 0 },
         '11' : { 'cost' : 7, 'bonus' : 124.8, 'bonus2' : 11, 'bonus3' : 0 },
         '12' : { 'cost' : 8, 'bonus' : 263.4, 'bonus2' : 12, 'bonus3' : 0 },
         '13' : { 'cost' : 9, 'bonus' : 595.3, 'bonus2' : 13, 'bonus3' : 0 },
         '14' : { 'cost' : 11, 'bonus' : 1530, 'bonus2' : 14, 'bonus3' : 0 },
         '15' : { 'cost' : 12, 'bonus' : 4210, 'bonus2' : 15, 'bonus3' : 0 },
         '16' : { 'cost' : 14, 'bonus' : 13000, 'bonus2' : 16, 'bonus3' : 0 },
         '17' : { 'cost' : 16, 'bonus' : 45200, 'bonus2' : 18, 'bonus3' : 0 },
         '18' : { 'cost' : 19, 'bonus' : 184000, 'bonus2' : 20, 'bonus3' : 0 },
         '19' : { 'cost' : 22, 'bonus' : 866000, 'bonus2' : 22, 'bonus3' : 0 },
         '20' : { 'cost' : 25, 'bonus' : 4690000, 'bonus2' : 24, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'cs'
       }
     },
     'ti' : {
       'active' : 1,
       'sort' : 14,
       'name' : '战略洞悉',
       'nickname' : 'Y3_1',
       'branch' : 'yellow',
       'bonus' : ' 英雄技能：乘数加成',
       'bonus2' : ' 英雄技能：加数加成',
       'bonus3' : -1,
       'tier' : 3,
       'prereq' : 'sow',
       'max' : 20,
       'type' : 'pct_pos',
       'type2' : 'pct_pos',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 2, 'bonus' : .002, 'bonus2' : .02, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : .0036, 'bonus2' : .044, 'bonus3' : 0 },
         '3' : { 'cost' : 3, 'bonus' : .0055, 'bonus2' : .07, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : .0076, 'bonus2' : .095, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : .0099, 'bonus2' : .121, 'bonus3' : 0 },
         '6' : { 'cost' : 4, 'bonus' : .0127, 'bonus2' : .148, 'bonus3' : 0 },
         '7' : { 'cost' : 5, 'bonus' : .0158, 'bonus2' : .176,  'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : .0193, 'bonus2' : .204, 'bonus3' : 0 },
         '9' : {  'cost' : 6, 'bonus' : .0234, 'bonus2' : .233, 'bonus3' : 0 },
         '10' : { 'cost' : 7, 'bonus' : .028, 'bonus2' : .263, 'bonus3' : 0 },
         '11' : { 'cost' : 8, 'bonus' : .0333, 'bonus2' : .293, 'bonus3' : 0 },
         '12' : { 'cost' : 9, 'bonus' : .0393, 'bonus2' : .324, 'bonus3' : 0 },
         '13' : { 'cost' : 11, 'bonus' : .0461, 'bonus2' : .356, 'bonus3' : 0 },
         '14' : { 'cost' : 12, 'bonus' : .0539, 'bonus2' : .388, 'bonus3' : 0 },
         '15' : { 'cost' : 14, 'bonus' : .0628, 'bonus2' : .421, 'bonus3' : 0 },
         '16' : { 'cost' : 16, 'bonus' : .073, 'bonus2' : .456, 'bonus3' : 0 },
         '17' : { 'cost' : 19, 'bonus' : .0846, 'bonus2' : .49, 'bonus3' : 0 },
         '18' : { 'cost' : 22, 'bonus' : .0978, 'bonus2' : .526, 'bonus3' : 0 },
         '19' : { 'cost' : 25, 'bonus' : .1129, 'bonus2' : .563, 'bonus3' : 0 },
         '20' : { 'cost' : 28, 'bonus' : .13, 'bonus2' : .6, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'hero'
       }
     },
     'coo' : {
       'active' : 1,
       'sort' : 15,
       'name' : '协同进攻',
       'nickname' : 'Y3_3',
       'branch' : 'yellow',
       'bonus' : ' 活跃时所有英雄伤害',
       'bonus2' : '秒钟 冷却',
       'bonus3' : -1,
       'tier' : 3,
       'prereq' : 'aas',
       'max' : 20,
       'type' : 'multiply',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 2, 'bonus' : 1.8, 'bonus2' : 0, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 2.5, 'bonus2' : -.5, 'bonus3' : 0 },
         '3' : { 'cost' : 3, 'bonus' : 3.9, 'bonus2' : -1, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : 6, 'bonus2' : -1.5, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 9.3, 'bonus2' : -2, 'bonus3' : 0 },
         '6' : { 'cost' : 4, 'bonus' : 15.7, 'bonus2' : -2.5, 'bonus3' : 0 },
         '7' : { 'cost' : 5, 'bonus' : 28.9, 'bonus2' : -3, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 53.2, 'bonus2' : -3.5, 'bonus3' : 0 },
         '9' : {  'cost' : 6, 'bonus' : 106.6, 'bonus2' : -4, 'bonus3' : 0 },
         '10' : { 'cost' : 7, 'bonus' : 231.4, 'bonus2' : -5, 'bonus3' : 0 },
         '11' : { 'cost' : 8, 'bonus' : 543.1, 'bonus2' : -6, 'bonus3' : 0 },
         '12' : { 'cost' : 9, 'bonus' : 1370, 'bonus2' : -7, 'bonus3' : 0 },
         '13' : { 'cost' : 11, 'bonus' : 4020, 'bonus2' : -8, 'bonus3' : 0 },
         '14' : { 'cost' : 12, 'bonus' : 12600, 'bonus2' : -9, 'bonus3' : 0 },
         '15' : { 'cost' : 14, 'bonus' : 44900, 'bonus2' : -10, 'bonus3' : 0 },
         '16' : { 'cost' : 16, 'bonus' : 181000, 'bonus2' : -11, 'bonus3' : 0 },
         '17' : { 'cost' : 19, 'bonus' : 873000, 'bonus2' : -12, 'bonus3' : 0 },
         '18' : { 'cost' : 22, 'bonus' : 4950000, 'bonus2' : -13, 'bonus3' : 0 },
         '19' : { 'cost' : 25, 'bonus' : 32600000, 'bonus2' : -14, 'bonus3' : 0 },
         '20' : { 'cost' : 28, 'bonus' : 248000000, 'bonus2' : -15, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'hero'
       }
     },
     'aaw' : {
       'active' : 1,
       'sort' : 16,
       'name' : '灵魂觉醒',
       'nickname' : 'Y4_1',
       'branch' : 'yellow',
       'bonus' : ' 全部英雄伤害每次点击',
       'bonus2' : -1,
       
       'tier' : 4,
       'prereq' : 'ti',
       'max' : 12,
       'type' : 'multiply',
       'type2' : -1,
       'type3' : 'add_skill',
       'levels' : {
         '1' : { 'cost' : 3, 'bonus' : 1.3, 'bonus2' : 0, 'bonus3' : 5 },
         '2' : { 'cost' : 4, 'bonus' : 1.5, 'bonus2' : 0, 'bonus3' : 5 },
         '3' : { 'cost' : 5, 'bonus' : 1.9, 'bonus2' : 0, 'bonus3' : 5 },
         '4' : { 'cost' : 7, 'bonus' : 2.4, 'bonus2' : 0, 'bonus3' : 5 },
         '5' : { 'cost' : 9, 'bonus' : 3.3, 'bonus2' : 0, 'bonus3' : 5 },
         '6' : { 'cost' : 12, 'bonus' : 4.7, 'bonus2' : 0, 'bonus3' : 5 },
         '7' : { 'cost' : 16, 'bonus' : 7.1, 'bonus2' : 0, 'bonus3' : 5 },
         '8' : { 'cost' : 21, 'bonus' : 11.6, 'bonus2' : 0, 'bonus3' : 5 },
         '9' : {  'cost' : 27, 'bonus' : 20.5, 'bonus2' : 0, 'bonus3' : 5 },
         '10' : { 'cost' : 35, 'bonus' : 39, 'bonus2' : 0, 'bonus3' : 5 },
         '11' : { 'cost' : 46, 'bonus' : 83, 'bonus2' : 0, 'bonus3' : 5 },
         '12' : { 'cost' : 60, 'bonus' : 195, 'bonus2' : 0, 'bonus3' : 5 }
       },
       'expo' : {
         'reduct' : 'hero'
       }
     },
     'as' : {
       'active' : 1,
       'sort' : 16,
       'name' : '锚定射击',
       'nickname' : 'Y4_3',
       'branch' : 'yellow',
       'bonus' : ' 眩晕伤害',
       'bonus2' : '秒钟 眩晕持续时间',
       'bonus3' : -1,
       'tier' : 4,
       'prereq' : 'coo',
       'max' : 12,
       'type' : 'multiply',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 3, 'bonus' : 3.5, 'bonus2' : .8, 'bonus3' : 0 },
         '2' : { 'cost' : 4, 'bonus' : 9.9, 'bonus2' : .9, 'bonus3' : 0 },
         '3' : { 'cost' : 5, 'bonus' : 32.2, 'bonus2' : 1, 'bonus3' : 0  },
         '4' : { 'cost' : 7, 'bonus' : 135.8, 'bonus2' : 1.1, 'bonus3' : 0 },
         '5' : { 'cost' : 9, 'bonus' : 728.7, 'bonus2' : 1.2, 'bonus3' : 0 },
         '6' : { 'cost' : 12, 'bonus' : 5430, 'bonus2' : 1.3, 'bonus3' : 0 },
         '7' : { 'cost' : 16, 'bonus' : 59500, 'bonus2' : 1.4,  'bonus3' : 0 },
         '8' : { 'cost' : 21, 'bonus' : 997000,  'bonus2' : 1.5, 'bonus3' : 0 },
         '9' : {  'cost' : 27, 'bonus' : 25900000, 'bonus2' : 1.6, 'bonus3' : 0 },
         '10' : { 'cost' : 35, 'bonus' : 1110000000, 'bonus2' : 1.7, 'bonus3' : 0 },
         '11' : { 'cost' : 46, 'bonus' : 85000000000, 'bonus2' : 1.8, 'bonus3' : 0 },
         '12' : { 'cost' : 60, 'bonus' : 11800000000000, 'bonus2' : 2, 'bonus3' : 0 }
       },
       'expo' : {
         'flat' : 'rev_cs'
       }
     },
     'lbr' : {
       'active' : 1,
       'sort' : 17,
       'name' : '极限突破',
       'nickname' : 'B1',
       'branch' : 'blue',
       'bonus' : ' 法力上限',
       'bonus2' : ' 法力回复',
       'bonus3' : -1,
       'tier' : 1,
       'prereq' : -1,
       'max' : 20,
       'type' : 'add_skill',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 5, 'bonus2' : .1, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 8, 'bonus2' : .228, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : 12, 'bonus2' : .373, 'bonus3' : 0  },
         '4' : { 'cost' : 3, 'bonus' : 19, 'bonus2' : .538, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 26, 'bonus2' : .727, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : 35, 'bonus2' : .941, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : 46, 'bonus2' : 1.185, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 62, 'bonus2' : 1.463, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : 80, 'bonus2' : 1.779, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : 103, 'bonus2' : 2.139, 'bonus3' : 0 },
         '11' : { 'cost' : 7, 'bonus' : 132, 'bonus2' : 2.549, 'bonus3' : 0 },
         '12' : { 'cost' : 8, 'bonus' : 168, 'bonus2' : 3.015, 'bonus3' : 0 },
         '13' : { 'cost' : 9, 'bonus' : 213, 'bonus2' : 3.546, 'bonus3' : 0 },
         '14' : { 'cost' : 11, 'bonus' : 269, 'bonus2' : 4.151, 'bonus3' : 0 },
         '15' : { 'cost' : 12, 'bonus' : 337, 'bonus2' : 4.839, 'bonus3' : 0 },
         '16' : { 'cost' : 14, 'bonus' : 421, 'bonus2' : 5.622, 'bonus3' : 0 },
         '17' : { 'cost' : 16, 'bonus' : 524, 'bonus2' : 6.514, 'bonus3' : 0 },
         '18' : { 'cost' : 19, 'bonus' : 652, 'bonus2' : 7.529, 'bonus3' : 0 },
         '19' : { 'cost' : 22, 'bonus' : 809, 'bonus2' : 8.684, 'bonus3' : 0 },
         '20' : { 'cost' : 25, 'bonus' : 1000, 'bonus2' : 10, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'hs'
       }
     },
     'mu' : {
       'active' : 1,
       'sort' : 18,
       'name' : '终极米达斯',
       'nickname' : 'B2_1',
       'branch' : 'blue',
       'bonus' : ' 米达斯之手黄金',
       'bonus2' : ' 仙女黄金',
       'bonus3' : -1,
       'tier' : 2,
       'prereq' : 'lbr',
       'max' : 20,
       'type' : 'multiply',
       'type2' : 'multiply',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 1.8, 'bonus2' : 1.2, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 3.2, 'bonus2' : 1.4, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : 5.8, 'bonus2' : 1.6, 'bonus3' : 0  },
         '4' : { 'cost' : 3, 'bonus' : 11.2, 'bonus2' : 2.1, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 21.9, 'bonus2' : 2.6, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : 42.6, 'bonus2' : 3.2, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : 89.8, 'bonus2' : 4.4, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 204.9, 'bonus2' : 6.3, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : 467.6, 'bonus2' : 9.1, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : 1150.3, 'bonus2' : 14, 'bonus3' : 0 },
         '11' : { 'cost' : 7, 'bonus' : 3044.2, 'bonus2' : 23, 'bonus3' : 0 },
         '12' : { 'cost' : 8, 'bonus' : 8647.5, 'bonus2' : 40, 'bonus3' : 0 },
         '13' : { 'cost' : 9, 'bonus' : 26300, 'bonus2' : 74, 'bonus3' : 0 },
         '14' : { 'cost' : 11, 'bonus' : 91300, 'bonus2' : 155, 'bonus3' : 0 },
         '15' : { 'cost' : 12, 'bonus' : 337000, 'bonus2' : 340, 'bonus3' : 0 },
         '16' : { 'cost' : 14, 'bonus' : 1410000, 'bonus2' : 831, 'bonus3' : 0 },
         '17' : { 'cost' : 16, 'bonus' : 6590000, 'bonus2' : 2245, 'bonus3' : 0 },
         '18' : { 'cost' : 19, 'bonus' : 36300000, 'bonus2' : 6989, 'bonus3' : 0 },
         '19' : { 'cost' : 22, 'bonus' : 232000000, 'bonus2' : 24844, 'bonus3' : 0 },
         '20' : { 'cost' : 25, 'bonus' : 1720000000, 'bonus2' : 100000, 'bonus3' : 0 }
       },
       'expo' : {
         'flat' : 'gold_phom'
       }
     },
     'ar' : {
       'active' : 1,
       'sort' : 19,
       'name' : '天使光辉',
       'nickname' : 'B2_2',
       'branch' : 'blue',
       'bonus' : ' 天上击伤害',
       'bonus2' : ' 天上击溅跳过',
       'bonus3' : -1,
       'tier' : 2,
       'prereq' : 'lbr',
       'max' : 20,
       'type' : 'multiply',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 2, 'bonus2' : 0, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 3.5, 'bonus2' : 1, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : 6.1, 'bonus2' : 1, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : 11.5, 'bonus2' : 2, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 21.7, 'bonus2' : 3, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : 40.8, 'bonus2' : 4, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : 82, 'bonus2' : 5,  'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 178, 'bonus2' : 6, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : 384, 'bonus2' : 7, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : 886, 'bonus2' : 8, 'bonus3' : 0 },
         '11' : { 'cost' : 7, 'bonus' : 2180, 'bonus2' : 10, 'bonus3' : 0 },
         '12' : { 'cost' : 8, 'bonus' : 5690, 'bonus2' : 12, 'bonus3' : 0 },
         '13' : { 'cost' : 9, 'bonus' : 15800, 'bonus2' : 14, 'bonus3' : 0 },
         '14' : { 'cost' : 11, 'bonus' : 49100, 'bonus2' : 16, 'bonus3' : 0 },
         '15' : { 'cost' : 12, 'bonus' : 161000, 'bonus2' : 18, 'bonus3' : 0 },
         '16' : { 'cost' : 14, 'bonus' : 589000, 'bonus2' : 20, 'bonus3' : 0 },
         '17' : { 'cost' : 16, 'bonus' : 2380000, 'bonus2' : 24, 'bonus3' : 0 },
         '18' : { 'cost' : 19, 'bonus' : 11000000, 'bonus2' : 29, 'bonus3' : 0 },
         '19' : { 'cost' : 22, 'bonus' : 58500000, 'bonus2' : 34, 'bonus3' : 0 },
         '20' : { 'cost' : 25, 'bonus' : 351000000, 'bonus2' : 40, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'hs'
       }
     },
     'pv' : {
       'active' : 1,
       'sort' : 20,
       'name' : '幽魂复仇',
       'nickname' : 'B2_3',
       'branch' : 'blue',
       'bonus' : ' 影分身伤害',
       'bonus2' : ' 攻击每秒',
       'bonus3' : -1,
       'tier' : 2,
       'prereq' : 'lbr',
       'max' : 20,
       'type' : 'multiply',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 1.5, 'bonus2' : .1, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 2, 'bonus2' : .21, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : 2.6, 'bonus2' : .33, 'bonus3' : 0  },
         '4' : { 'cost' : 3, 'bonus' : 3.7, 'bonus2' : .46, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 5.3, 'bonus2' : .59, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : 7.6, 'bonus2' : .74, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : 11.9, 'bonus2' : .89, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 20.2, 'bonus2' : 1.05, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : 34.5, 'bonus2' : 1.22, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : 64, 'bonus2' : 1.41, 'bonus3' : 0 },
         '11' : { 'cost' : 7, 'bonus' : 128.4, 'bonus2' : 1.6, 'bonus3' : 0 },
         '12' : { 'cost' : 8, 'bonus' : 278.4, 'bonus2' : 1.81, 'bonus3' : 0 },
         '13' : { 'cost' : 9, 'bonus' : 650.4, 'bonus2' : 2.03, 'bonus3' : 0 },
         '14' : { 'cost' : 11, 'bonus' : 1750, 'bonus2' : 2.26, 'bonus3' : 0 },
         '15' : { 'cost' : 12, 'bonus' : 5050, 'bonus2' : 2.51, 'bonus3' : 0 },
         '16' : { 'cost' : 14, 'bonus' : 16600, 'bonus2' : 2.77, 'bonus3' : 0 },
         '17' : { 'cost' : 16, 'bonus' : 61700, 'bonus2' : 3.05, 'bonus3' : 0 },
         '18' : { 'cost' : 19, 'bonus' : 273000, 'bonus2' : 3.35, 'bonus3' : 0 },
         '19' : { 'cost' : 22, 'bonus' : 1420000, 'bonus2' : 3.66, 'bonus3' : 0 },
         '20' : { 'cost' : 25, 'bonus' : 8610000, 'bonus2' : 4, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'sc'
       }
     },
     'fc' : {
       'active' : 1,
       'sort' : 21,
       'name' : '仙女魔力',
       'nickname' : 'B3_1',
       'branch' : 'blue',
       'bonus' : ' 多重仙女几率',
       'bonus2' : '秒钟 仙女重生冷却',
       'bonus3' : -1,
       'tier' : 3,
       'prereq' : 'mu',
       'max' : 10,
       'type' : 'pct_pos',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 2, 'bonus' : .04, 'bonus2' : -4, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : .16, 'bonus2' : -8.6, 'bonus3' : 0 },
         '3' : { 'cost' : 3, 'bonus' : .35, 'bonus2' : -13.5, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : .54, 'bonus2' : -18.8, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : .75, 'bonus2' : -24.5, 'bonus3' : 0 },
         '6' : { 'cost' : 4, 'bonus' : 1.03, 'bonus2' : -30.6, 'bonus3' : 0 },
         '7' : { 'cost' : 5, 'bonus' : 1.38, 'bonus2' : -37.2, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 1.76, 'bonus2' : -44.2, 'bonus3' : 0 },
         '9' : {  'cost' : 6, 'bonus' : 2.21, 'bonus2' : -51.8, 'bonus3' : 0 },
         '10' : { 'cost' : 7, 'bonus' : 2.75, 'bonus2' : -60, 'bonus3' : 0 }
       },
       'expo' : {
         'gold' : [
           'fairy',
         ]
       }
     },
     'ms' : {
       'active' : 1,
       'sort' : 22,
       'name' : '法力虹吸',
       'nickname' : 'B3_2',
       'branch' : 'blue',
       'bonus' : ' 法力回复能力',
       'bonus2' : -1,
       
       'tier' : 3,
       'prereq' : 'ar',
       'max' : 20,
       'type' : 'pct_pos',
       'type2' : -1,
       'type3' : 'pct_pos',
       'levels' : {
         '1' : { 'cost' : 2, 'bonus' : .0005, 'bonus2' : 0, 'bonus3' : .0005 },
         '2' : { 'cost' : 2, 'bonus' : .0007, 'bonus2' : 0, 'bonus3' : .0005 },
         '3' : { 'cost' : 3, 'bonus' : .0009, 'bonus2' : 0, 'bonus3' : .0005  },
         '4' : { 'cost' : 3, 'bonus' : .0012, 'bonus2' : 0, 'bonus3' : .0005 },
         '5' : { 'cost' : 3, 'bonus' : .0015, 'bonus2' : 0, 'bonus3' : .0005 },
         '6' : { 'cost' : 4, 'bonus' : .0019, 'bonus2' : 0, 'bonus3' : .0005 },
         '7' : { 'cost' : 5, 'bonus' : .0024, 'bonus2' : 0, 'bonus3' : .0005 },
         '8' : { 'cost' : 5, 'bonus' : .003, 'bonus2' : 0, 'bonus3' : .0005 },
         '9' : {  'cost' : 6, 'bonus' : .0036, 'bonus2' : 0, 'bonus3' : .0005 },
         '10' : { 'cost' : 7, 'bonus' : .0044, 'bonus2' : 0, 'bonus3' : .0005 },
         '11' : { 'cost' : 8, 'bonus' : .0053, 'bonus2' : 0, 'bonus3' : .0005 },
         '12' : { 'cost' : 9, 'bonus' : .0063, 'bonus2' : 0, 'bonus3' : .0005 },
         '13' : { 'cost' : 11, 'bonus' : .0075, 'bonus2' : 0, 'bonus3' : .0005 },
         '14' : { 'cost' : 12, 'bonus' : .0089, 'bonus2' : 0, 'bonus3' : .0005 },
         '15' : { 'cost' : 14, 'bonus' : .0106, 'bonus2' : 0, 'bonus3' : .0005 },
         '16' : { 'cost' : 16, 'bonus' : .0125, 'bonus2' : 0, 'bonus3' : .0005 },
         '17' : { 'cost' : 19, 'bonus' : .0148, 'bonus2' : 0, 'bonus3' : .0005 },
         '18' : { 'cost' : 22, 'bonus' : .0174, 'bonus2' : 0, 'bonus3' : .0005 },
         '19' : { 'cost' : 25, 'bonus' : .0205, 'bonus2' : 0, 'bonus3' : .0005 },
         '20' : { 'cost' : 28, 'bonus' : .024, 'bonus2' : 0, 'bonus3' : .0005 }
       },
       'expo' : {
         'reduct' : 'tap'
       }
     },
     'ed' : {
       'active' : 1,
       'sort' : 23,
       'name' : '永恒黑暗',
       'nickname' : 'B3_3',
       'branch' : 'blue',
       'bonus' : '秒钟 阴影克隆持续时间',
       'bonus2' : ' 阴影克隆飞溅跳过',
       'bonus3' : -1,
       'tier' : 3,
       'prereq' : 'pv',
       'max' : 20,
       'type' : 'add_skill',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 2, 'bonus' : 2, 'bonus2' : 0, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 4.5, 'bonus2' : 1, 'bonus3' : 0 },
         '3' : { 'cost' : 3, 'bonus' : 8.9, 'bonus2' : 1, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : 13.3, 'bonus2' : 2, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 17.7, 'bonus2' : 3, 'bonus3' : 0 },
         '6' : { 'cost' : 4, 'bonus' : 24.1, 'bonus2' : 4, 'bonus3' : 0 },
         '7' : { 'cost' : 5, 'bonus' : 32.8, 'bonus2' : 5, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 41.5, 'bonus2' : 6, 'bonus3' : 0 },
         '9' : {  'cost' : 6, 'bonus' : 52.6, 'bonus2' : 7, 'bonus3' : 0 },
         '10' : { 'cost' : 7, 'bonus' : 66.2, 'bonus2' : 8, 'bonus3' : 0 },
         '11' : { 'cost' : 8, 'bonus' : 82.5, 'bonus2' : 10, 'bonus3' : 0 },
         '12' : { 'cost' : 9, 'bonus' : 101.7, 'bonus2' : 12, 'bonus3' : 0 },
         '13' : { 'cost' : 11, 'bonus' : 126.7, 'bonus2' : 14, 'bonus3' : 0 },
         '14' : { 'cost' : 12, 'bonus' : 154.9, 'bonus2' : 16, 'bonus3' : 0 },
         '15' : { 'cost' : 14, 'bonus' : 189.5, 'bonus2' : 18, 'bonus3' : 0 },
         '16' : { 'cost' : 16, 'bonus' : 231, 'bonus2' : 20, 'bonus3' : 0 },
         '17' : { 'cost' : 19, 'bonus' : 283.1, 'bonus2' : 24, 'bonus3' : 0 },
         '18' : { 'cost' : 22, 'bonus' : 346.7, 'bonus2' : 29, 'bonus3' : 0 },
         '19' : { 'cost' : 25, 'bonus' : 422.2, 'bonus2' : 34, 'bonus3' : 0 },
         '20' : { 'cost' : 28, 'bonus' : 510, 'bonus2' : 40, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'sc'
       }
     },
     'mm' : {
       'active' : 1,
       'sort' : 24,
       'name' : '曼尼马纳',
       'nickname' : 'B4_1',
       'branch' : 'blue',
       'bonus' : ' 法力补充',
       'bonus2' : ' 重生几率',
       'bonus3' : -1,
       'tier' : 4,
       'prereq' : 'fc',
       'max' : 12,
       'type' : 'add_skill',
       'type2' : 'pct_pos',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 3, 'bonus' : 2, 'bonus2' : .005, 'bonus3' : 0 },
         '2' : { 'cost' : 4, 'bonus' : 4, 'bonus2' : .005, 'bonus3' : 0 },
         '3' : { 'cost' : 5, 'bonus' : 6.5, 'bonus2' : .005, 'bonus3' : 0  },
         '4' : { 'cost' : 7, 'bonus' : 10, 'bonus2' : .005, 'bonus3' : 0 },
         '5' : { 'cost' : 9, 'bonus' : 14.5, 'bonus2' : .005, 'bonus3' : 0 },
         '6' : { 'cost' : 12, 'bonus' : 20.5, 'bonus2' : .005, 'bonus3' : 0 },
         '7' : { 'cost' : 16, 'bonus' : 28.5, 'bonus2' : .005, 'bonus3' : 0 },
         '8' : { 'cost' : 21, 'bonus' : 39, 'bonus2' : .005, 'bonus3' : 0 },
         '9' : {  'cost' : 27, 'bonus' : 52.5, 'bonus2' : .005, 'bonus3' : 0 },
         '10' : { 'cost' : 35, 'bonus' : 70, 'bonus2' : .005, 'bonus3' : 0 },
         '11' : { 'cost' : 46, 'bonus' : 93, 'bonus2' : .005, 'bonus3' : 0 },
         '12' : { 'cost' : 60, 'bonus' : 123, 'bonus2' : .005, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'hs'
       }
     },
     'ls' : {
       'active' : 1,
       'sort' : 25,
       'name' : '闪电打击',
       'nickname' : 'B4_2',
       'branch' : 'blue',
       'bonus' : ' 巨人生命减少',
       'bonus2' : ' 几率每次点击',
       'bonus3' : -1,
       'tier' : 4,
       'prereq' : 'ms',
       'max' : 12,
       'type' : 'pct_pos',
       'type2' : 'pct_pos',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 3, 'bonus' : .115, 'bonus2' : .0075, 'bonus3' : 0 },
         '2' : { 'cost' : 4, 'bonus' : .15, 'bonus2' : .0087, 'bonus3' : 0 },
         '3' : { 'cost' : 5, 'bonus' : .185, 'bonus2' : .01, 'bonus3' : 0 },
         '4' : { 'cost' : 7, 'bonus' : .22, 'bonus2' : .0113, 'bonus3' : 0 },
         '5' : { 'cost' : 9, 'bonus' : .255, 'bonus2' : .0127, 'bonus3' : 0 },
         '6' : { 'cost' : 12, 'bonus' : .29, 'bonus2' : .0142, 'bonus3' : 0 },
         '7' : { 'cost' : 16, 'bonus' : .325, 'bonus2' : .0158,  'bonus3' : 0 },
         '8' : { 'cost' : 21, 'bonus' : .36, 'bonus2' : .0174, 'bonus3' : 0 },
         '9' : {  'cost' : 27, 'bonus' : .395, 'bonus2' : .0192, 'bonus3' : 0 },
         '10' : { 'cost' : 35, 'bonus' : .43, 'bonus2' : .021, 'bonus3' : 0 },
         '11' : { 'cost' : 46, 'bonus' : .465, 'bonus2' : .023, 'bonus3' : 0 },
         '12' : { 'cost' : 60, 'bonus' : .5, 'bonus2' : .025, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'tap_hs'
       }
     },
     'ds' : {
       'active' : 1,
       'sort' : 26,
       'name' : '相位转移',
       'nickname' : 'B4_3',
       'branch' : 'blue',
       'bonus' : ' 主动技能的主要效果',
       'bonus2' : ' 主动技能计时器倒数速度',
       'bonus3' : -1,
       'tier' : 4,
       'prereq' : 'ed',
       'max' : 12,
       'type' : 'multiply',
       'type2' : 'pct_pos',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 3, 'bonus' : 1.6, 'bonus2' : .04, 'bonus3' : 0 },
         '2' : { 'cost' : 4, 'bonus' : 2.1, 'bonus2' : .08, 'bonus3' : 0 },
         '3' : { 'cost' : 5, 'bonus' : 2.9, 'bonus2' : .12, 'bonus3' : 0  },
         '4' : { 'cost' : 7, 'bonus' : 4.2, 'bonus2' : .16, 'bonus3' : 0 },
         '5' : { 'cost' : 9, 'bonus' : 6.4, 'bonus2' : .2, 'bonus3' : 0 },
         '6' : { 'cost' : 12, 'bonus' : 10.7, 'bonus2' : .24, 'bonus3' : 0 },
         '7' : { 'cost' : 16, 'bonus' : 19.6, 'bonus2' : .28, 'bonus3' : 0 },
         '8' : { 'cost' : 21, 'bonus' : 40, 'bonus2' : .32, 'bonus3' : 0 },
         '9' : {  'cost' : 27, 'bonus' : 91, 'bonus2' : .36, 'bonus3' : 0 },
         '10' : { 'cost' : 35, 'bonus' : 235, 'bonus2' : .4, 'bonus3' : 0 },
         '11' : { 'cost' : 46, 'bonus' : 700, 'bonus2' : .45, 'bonus3' : 0 },
         '12' : { 'cost' : 60, 'bonus' : 2425, 'bonus2' : .5, 'bonus3' : 0 }
       },
       'expo' : {
         'sum' : 'skill'
       }
     },
     'mt' : {
       'active' : 1,
       'sort' : 28,
       'name' : '盗圣',
       'nickname' : 'G1',
       'branch' : 'green',
       'bonus' : ' 所有黄金',
       'bonus2' : ' 非活跃黄金',
       'bonus3' : -1,
       'tier' : 1,
       'prereq' : -1,
       'max' : 20,
       'type' : 'multiply',
       'type2' : 'multiply',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 1.6, 'bonus2' : 1.4, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 2.8, 'bonus2' : 2.1, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : 4.9, 'bonus2' : 3.2, 'bonus3' : 0  },
         '4' : { 'cost' : 3, 'bonus' : 9.2, 'bonus2' : 5, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 17.3, 'bonus2' : 7.9, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : 32.6, 'bonus2' : 12.3, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : 65.9, 'bonus2' : 20, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 142.2, 'bonus2' : 33.7, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : 307.3, 'bonus2' : 56.6, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : 708.6, 'bonus2' : 98.2, 'bonus3' : 0 },
         '11' : { 'cost' : 7, 'bonus' : 1740, 'bonus2' : 176, 'bonus3' : 0 },
         '12' : { 'cost' : 8, 'bonus' : 4550, 'bonus2' : 325, 'bonus3' : 0 },
         '13' : { 'cost' : 9, 'bonus' : 12600, 'bonus2' : 619, 'bonus3' : 0 },
         '14' : { 'cost' : 11, 'bonus' : 39300, 'bonus2' : 1250, 'bonus3' : 0 },
         '15' : { 'cost' : 12, 'bonus' : 129000, 'bonus2' : 2590, 'bonus3' : 0 },
         '16' : { 'cost' : 14, 'bonus' : 471000, 'bonus2' : 5650, 'bonus3' : 0 },
         '17' : { 'cost' : 16, 'bonus' : 1900000, 'bonus2' : 13000, 'bonus3' : 0 },
         '18' : { 'cost' : 19, 'bonus' : 8830000, 'bonus2' : 32000, 'bonus3' : 0 },
         '19' : { 'cost' : 22, 'bonus' : 46800000, 'bonus2' : 84100, 'bonus3' : 0 },
         '20' : { 'cost' : 25, 'bonus' : 281000000, 'bonus2' : 235000, 'bonus3' : 0 }
       },
       'expo' : {
         'flat' : 'inactive_gold'
       }
     },
     'an' : {
       'active' : 1,
       'sort' : 28,
       'name' : '刺杀',
       'nickname' : 'G2_1',
       'branch' : 'green',
       'bonus' : ' 致命打击伤害',
       'bonus2' : ' 致命打击几率',
       'bonus3' : -1,
       'tier' : 2,
       'prereq' : 'mt',
       'max' : 20,
       'type' : 'multiply',
       'type2' : 'add_skill',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 1.6, 'bonus2' : 2, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 2.3, 'bonus2' : 4.5, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : 3.3, 'bonus2' : 8.9, 'bonus3' : 0  },
         '4' : { 'cost' : 3, 'bonus' : 5.2, 'bonus2' : 13.3, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 8.2, 'bonus2' : 17.7, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : 12.8, 'bonus2' : 24.1, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : 21.9, 'bonus2' : 32.8, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 40.4, 'bonus2' : 41.5, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : 74.5, 'bonus2' : 52.6, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : 148.3, 'bonus2' : 66.2, 'bonus3' : 0 },
         '11' : { 'cost' : 7, 'bonus' : 317.8, 'bonus2' : 82.5, 'bonus3' : 0 },
         '12' : { 'cost' : 8, 'bonus' : 731.6, 'bonus2' : 101.7, 'bonus3' : 0 },
         '13' : { 'cost' : 9, 'bonus' : 1800, 'bonus2' : 126.7, 'bonus3' : 0 },
         '14' : { 'cost' : 11, 'bonus' : 5070, 'bonus2' : 154.9, 'bonus3' : 0 },
         '15' : { 'cost' : 12, 'bonus' : 15200, 'bonus2' : 189.5, 'bonus3' : 0 },
         '16' : { 'cost' : 14, 'bonus' : 51300, 'bonus2' : 231, 'bonus3' : 0 },
         '17' : { 'cost' : 16, 'bonus' : 194000, 'bonus2' : 283.1, 'bonus3' : 0 },
         '18' : { 'cost' : 19, 'bonus' : 860000, 'bonus2' : 346.7, 'bonus3' : 0 },
         '19' : { 'cost' : 22, 'bonus' : 4420000, 'bonus2' : 422.2, 'bonus3' : 0 },
         '20' : { 'cost' : 25, 'bonus' : 26100000, 'bonus2' : 510, 'bonus3' : 0 }
       },
       'expo' : {
         'reduct' : 'ds'
       }
     },
     'sm' : {
       'active' : 1,
       'sort' : 29,
       'name' : '无声行军',
       'nickname' : 'G2_2',
       'branch' : 'green',
       'bonus' : ' 无效损伤',
       'bonus2' : '秒钟 无效的产卵时间',
       'bonus3' : ' 离线状态最大关卡',
       'tier' : 2,
       'prereq' : 'mt',
       'max' : 10,
       'type' : 'multiply',
       'type2' : 'add_skill',
       'type3' : 'pct_pos',
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 1, 'bonus2' : 0, 'bonus3' : .99 },
         '2' : { 'cost' : 2, 'bonus' : 2.1, 'bonus2' : .05, 'bonus3' : .99 },
         '3' : { 'cost' : 2, 'bonus' : 3.8, 'bonus2' : .1, 'bonus3' : .99 },
         '4' : { 'cost' : 3, 'bonus' : 7.5, 'bonus2' : .2, 'bonus3' : .99 },
         '5' : { 'cost' : 3, 'bonus' : 14.4, 'bonus2' : .3, 'bonus3' : .99 },
         '6' : { 'cost' : 3, 'bonus' : 27.2, 'bonus2' : .42, 'bonus3' : .99 },
         '7' : { 'cost' : 4, 'bonus' : 59, 'bonus2' : .54, 'bonus3' : .99 },
         '8' : { 'cost' : 5, 'bonus' : 146, 'bonus2' : .66, 'bonus3' : .99 },
         '9' : {  'cost' : 5, 'bonus' : 360, 'bonus2' : .78, 'bonus3' : .99 },
         '10' : { 'cost' : 6, 'bonus' : 1000, 'bonus2' : .9, 'bonus3' : .99 }
       },
       'expo' : {
         'flat' : 'inactive'
       }
     },
     'ab' : {
       'active' : 1,
       'sort' : 30,
       'name' : '伏击',
       'nickname' : 'G2_3',
       'branch' : 'green',
       'bonus' : ' 最大巨人重生数',
       'bonus2' : ' 多重巨人重生几率',
       'bonus3' : -1,
       'tier' : 2,
       'prereq' : 'mt',
       'max' : 10,
       'type' : 'add_skill',
       'type2' : 'pct_pos',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 1, 'bonus' : 1, 'bonus2' : .01, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : 2, 'bonus2' : .016, 'bonus3' : 0 },
         '3' : { 'cost' : 2, 'bonus' : 4, 'bonus2' : .024, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : 6, 'bonus2' : .036, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 8, 'bonus2' : .052, 'bonus3' : 0 },
         '6' : { 'cost' : 3, 'bonus' : 10, 'bonus2' : .075, 'bonus3' : 0 },
         '7' : { 'cost' : 4, 'bonus' : 12, 'bonus2' : .107, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 14, 'bonus2' : .151, 'bonus3' : 0 },
         '9' : {  'cost' : 5, 'bonus' : 16, 'bonus2' : .213, 'bonus3' : 0 },
         '10' : { 'cost' : 6, 'bonus' : 20, 'bonus2' : .3, 'bonus3' : 0 }
       },
       'expo' : {
         'flat' : 'inactive_phom'
       }
     },
     'tv' : {
       'active' : 1,
       'sort' : 31,
       'name' : '暮光面纱',
       'nickname' : 'G3_1',
       'branch' : 'green',
       'bonus' : ' 非活跃状态下宠物伤害',
       'bonus2' : ' 宠物致命打击伤害',
       'bonus3' : -1,
       'tier' : 3,
       'prereq' : 'an',
       'max' : 10,
       'type' : 'pct_pos',
       'type2' : 'multiply',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 2, 'bonus' : .01, 'bonus2' : 1, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : .03, 'bonus2' : 1.3, 'bonus3' : 0 },
         '3' : { 'cost' : 3, 'bonus' : .128, 'bonus2' : 1.9, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : .541, 'bonus2' : 2.7, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 2.29, 'bonus2' : 3.8, 'bonus3' : 0 },
         '6' : { 'cost' : 4, 'bonus' : 13, 'bonus2' : 5.8, 'bonus3' : 0 },
         '7' : { 'cost' : 5, 'bonus' : 96, 'bonus2' : 9.5, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 706, 'bonus2' : 15.5, 'bonus3' : 0 },
         '9' : {  'cost' : 6, 'bonus' : 6551, 'bonus2' : 26.9, 'bonus3' : 0 },
         '10' : { 'cost' : 7, 'bonus' : 75000, 'bonus2' : 50, 'bonus3' : 0 }
       },
       'expo' : {
         'flat' : 'inactive_pet'
       }
     },
     'gs' : {
       'active' : 1,
       'sort' : 32,
       'name' : '幽灵战舰',
       'nickname' : 'G3_2',
       'branch' : 'green',
       'bonus' : ' 非活跃状态下部落战舰伤害',
       'bonus2' : ' 部落致命打击伤害',
       'bonus3' : -1,
       'tier' : 3,
       'prereq' : 'sm',
       'max' : 10,
       'type' : 'pct_pos',
       'type2' : 'multiply',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 2, 'bonus' : .01, 'bonus2' : 1, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : .03, 'bonus2' : 1.3, 'bonus3' : 0 },
         '3' : { 'cost' : 3, 'bonus' : .128, 'bonus2' : 1.9, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : .541, 'bonus2' : 2.7, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 2.29, 'bonus2' : 3.8, 'bonus3' : 0 },
         '6' : { 'cost' : 4, 'bonus' : 13, 'bonus2' : 5.8, 'bonus3' : 0 },
         '7' : { 'cost' : 5, 'bonus' : 96, 'bonus2' : 9.5, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 706, 'bonus2' : 15.5, 'bonus3' : 0 },
         '9' : {  'cost' : 6, 'bonus' : 6551, 'bonus2' : 26.9, 'bonus3' : 0 },
         '10' : { 'cost' : 7, 'bonus' : 75000, 'bonus2' : 50, 'bonus3' : 0 }
       },
       'expo' : {
         'flat' : 'inactive_ship'
       }
     },
     'sa' : {
       'active' : 1,
       'sort' : 33,
       'name' : '暗影刺杀',
       'nickname' : 'G3_3',
       'branch' : 'green',
       'bonus' : ' 非活跃状态下影分身伤害',
       'bonus2' : ' 影分身致命打击伤害',
       'bonus3' : -1,
       'tier' : 3,
       'prereq' : 'ab',
       'max' : 10,
       'type' : 'pct_pos',
       'type2' : 'multiply',
       'type3' : -1,
       'levels' : {
         '1' : { 'cost' : 2, 'bonus' : .01, 'bonus2' : 1, 'bonus3' : 0 },
         '2' : { 'cost' : 2, 'bonus' : .03, 'bonus2' : 1.3, 'bonus3' : 0 },
         '3' : { 'cost' : 3, 'bonus' : .128, 'bonus2' : 1.9, 'bonus3' : 0 },
         '4' : { 'cost' : 3, 'bonus' : .541, 'bonus2' : 2.7, 'bonus3' : 0 },
         '5' : { 'cost' : 3, 'bonus' : 2.29, 'bonus2' : 3.8, 'bonus3' : 0 },
         '6' : { 'cost' : 4, 'bonus' : 13, 'bonus2' : 5.8, 'bonus3' : 0 },
         '7' : { 'cost' : 5, 'bonus' : 96, 'bonus2' : 9.5, 'bonus3' : 0 },
         '8' : { 'cost' : 5, 'bonus' : 706, 'bonus2' : 15.5, 'bonus3' : 0 },
         '9' : {  'cost' : 6, 'bonus' : 6551, 'bonus2' : 26.9, 'bonus3' : 0 },
         '10' : { 'cost' : 7, 'bonus' : 75000, 'bonus2' : 50, 'bonus3' : 0 }
       },
       'expo' : {
         'flat' : 'inactive_clone'
       }
     }
   }
 };
 